canonical/charmcraft

setup.py
Installing via pip requires the `charmcraft.commands` module to be included in the list of modules to install, so switching to a setuptools convenience function that finds all available modules.
The `charmcraft` entrypoint was also pointing at the `main` module instead of the `main` function.
=> Fix pip installation

charmcraft/commands/version.py, charmcraft/main.py, setup.py, tests/test_main.py
This was previously included in the `build` branch, separated here so the other one is more focused.
=> Kill bogus commands, and log when an error happens.

charmcraft/commands/build.py
We're launching the charm via dispatch even when dispatch is not
supported: this means we need to set up JUJU_DISPATCH_PATH ourselves
if it isn't done for us.
=> build: set JUJU_DISPATCH_PATH so we get the right hook

tests/commands/test_build.py
Avoid leaving behind a zip after tests.
Run test_build_basic_complete_structure in tmp_path as done in
test_build_package_tree_structure and test_build_package_name. The
latter two call builder.handle_package(), which writes the zip. The
former calls builder.run(), which gets there indirectly.
=> Put complete-structure test zip under tmp_path

charmcraft/commands/store/__init__.py, charmcraft/commands/store/store.py, charmcraft/main.py, requirements.txt, tests/commands/test_store_api.py, tests/commands/test_store_client.py, tests/commands/test_store_commands.py
Note that this new layer returns hard-defined structures to the commands (not leaking whatever the store returns). IOW, all dealing-with-store issues are isolated from the commands.
Also I started using `tabulate` for the Whoami command; it may look as overkill for just that, but will use tabulate for other commands in subsequent branches, so let's start here...
This is a work preparing for bringing more commands later (#62).
=> A small refactor creating a "store api" layer between commands and the client

charmcraft/commands/store/__init__.py, tests/commands/test_store_commands.py
I just isolated a helper function to get the charm name from the metadata file, and improved the tests history around that.
Also sneaked in the new domain for the Store API base url.
=> Work in preparation for the list-revisions branch.

charmcraft/__init__.py, charmcraft/version.py, setup.py
Also drop unused and untested VERSION. It doesn't work well with the
PEP440 suffixes, and if we need something like that using the standard
library's packaging.version.Version directly would be better (but as
long as our versions are pep-compliant users can simply
packaging.version.parse() our version and things work).
=> get version from git

charmcraft/commands/build.py, tests/commands/test_build.py
fixes: #80
This is the quick fix for issue #80 about adding templates to the built
charm. Ultimately, we want to fix this with issue #39 and handling
.jujuignore properly. However, we feel that ended up bigger than we
could handle for 0.3, and this at least gets people unblocked in the
next release until we land support for jujuignore.
=> charmcraft/commands/build.py: include 'templates' directory

charmcraft/commands/build.py, charmcraft/jujuignore.py, tests/commands/test_build.py, tests/test_jujuignore.py
This adds the ability for JujuIgnore to pull in the default ignores and extend them with .jujuignore contents.
I don't have tests around the walk functionality, but I figured I would leave it in there to show you how I was thinking it would look.
=> charmcraft/jujuignore.py: Allow extending the list of patterns.

tests/commands/test_init.py, tests/conftest.py
=> a couple of fixes for tests

charmcraft/commands/build.py, tests/commands/test_build.py
This makes 'charmcraft build' work even when running using the pip
shipped in bionic, which is a bit "off".
fixes: #102
=> cope with bionic's slightly broken pip3 command

charmcraft/main.py, tests/test_main.py
This was broken because argparse overwrites the global parser names with
the command's subparser names (so, when you did `charmcraft -v cmd`, it
got `.verbose` in False because the command has it in False, even if
global was True.
=> Fixed global options behaviour.

charmcraft/logsetup.py, charmcraft/main.py, tests/test_logsetup.py, tests/test_main.py
Moved out the the version logging from Dispatcher's init to the
MessageHandler, which will always send it to the file (first thing after
configuring that part of the logging) and to the terminal when the mode
goes verbose.
This is part of #48, but not of all it. It's what was important,
though, other two messages remain un-shown because of initialization
order, but those two messages will go away (or at least change heavily)
when the bootstrap refactor is done (see #139).
=> Always log the charmcraft version when indicated.

tests/commands/test_init.py
The code "env_path,) = env_paths" assumes that env_paths always has exactly one value in it. This breaks if your virtualenv adds more than one path.
=> fix PYTHONPATH correctly

charmcraft/cmdbase.py, charmcraft/commands/build.py, charmcraft/commands/init.py, charmcraft/commands/store/__init__.py, charmcraft/commands/version.py, charmcraft/helptexts.py, tests/factory.py, tests/test_help.py
For this I had to add a 'common' attribute to commands, to flag those are of "common use" (the "common" term was UX used in the docs).
Not integrated yet, this is part of the [big adjust help process](https://github.com/canonical/charmcraft/pull/153).
This PR includes [this previous one](https://github.com/canonical/charmcraft/pull/154).
=> Produce the default help text.

.travis.yml, charmcraft/commands/build.py, tests/commands/test_build.py
When using e.g. vagrant build fails because using hard links is not allowed.
Could catching the permission exception and attempting to copy the file instead be a way to manage builds in vagrant?
https://github.com/canonical/charmcraft/issues/151
=> when failing to create hard link attempt to use shutil.copy2

charmcraft/cmdbase.py, charmcraft/logsetup.py, charmcraft/main.py, tests/test_logsetup.py
Specifically:
- support "argsparsing" option in CommandError to just present the message to the user (this will be refactored heavily in the short future when we change how all messages are sent to the user, but we need it now to just show the help)
- Added a small helper to check for options in the arguments (which will be more used in the next branch).
=> Two small details before integrating help messages to main.

charmcraft/main.py, tests/test_main.py
Specifically:
- improved a comment about `COMMAND_GROUPS`
- changed the `test_dispatcher_command_execution_ok` test to verify what it was verifying, but without needing to have access to the instantiated object
- fixed how the `test_main_ok/no_args/controlled_error/etc` tests were patching the message handler and asserting it was properly called
=> Small improvements in preparation for the commands refactor branch.

charmcraft/main.py, tests/test_help.py, tests/test_main.py
For this I pre-parsed the sysargs, which moved ourselves to a MUCH SIMPLER use of ArgumentParser, as there are no more "commands" involved at that level.
Of course we're still using ArgumentParser, but only for each command.
Everything got MUCH MORE SIMPLE now, as there is quite less fiddling with ArgumentParser internals.
Sorry fo the length of the branch, but I improved several tests, added corner cases to others, and created a couple of new ones.
=> Load only the indicated command (if any), not everything in advance.

charmcraft/commands/build.py, charmcraft/commands/store/__init__.py, charmcraft/helptexts.py, charmcraft/main.py, tests/test_help.py
Several small improvements in the help texts all around, plus a big change: now the columns are "aligned to the center".
This is how it now looks the general help, for example:
```
$ fades -r requirements.txt -m charmcraft 
Usage:
charmcraft [help] <command>
Summary:
Charmcraft provides a streamlined, powerful, opinionated and
flexible tool to develop, package and manage the lifecycle of
Juju charm publication, particularly charms written within
the Operator Framework.
Global options:
-h, --help:  Show this help message and exit.
-v, --verbose:  More verbose and show debug information.
-q, --quiet:  Only show warnings and errors, not progress.
Starter commands:
build:  Build the charm.
help:  Provide help on charmcraft usage.
init:  Initialize a directory to be a charm project.
names: …
```
=> Improvements per ux review

charmcraft/templates/init/src/charm.py.j2
This PR changes the template for new charms to make use of the more user-friendly "self.config" alias discussed here:
https://discourse.juju.is/t/first-steps-with-the-operator-framework/3006/20?u=erik-lonroth
It makes the charming experience somewhat more casual-programmer-friendly
=> Make use of the self.config alias

charmcraft/main.py, tests/test_help.py
This was because we had two `-h/--help` options, one which is the global one (that works for the tool in general and for each command, as with any global option), and other specific for the command added by `ArgumentParser`. The fix is to tell `ArgumentParser` to not automatically add a help option.
Regarding tests, no new one was needed, just improved the current ones to stop hiding duplicates.
=> Avoid a duplicated -h/--help option when getting help for a command.

charmcraft/commands/init.py, charmcraft/main.py, tests/test_help.py, tests/test_main.py
Before this change, asking for help would always return with error.
This made testing actually asking for help hard, so we didn't, so we
never exercised the actual command parser, so a bug snuck in. This
changes things so that help returns with error only when actually in
error, and adds a test that asks for help over all commands, meaning
we exercise all the parsers, so we would actually catch this bug.
Fixes: #210
=> Exercise command parsers.

charmcraft/commands/store/__init__.py, charmcraft/commands/store/store.py, charmcraft/main.py, tests/commands/test_store_api.py, tests/commands/test_store_commands.py
This adds the command itself, and the supporting method in the store layer.
For ListLibCommand:
- it can run standalone, or with a given charm name
- when standalone, it will try to access metadata.yaml, and if there it will list all libraries for that charm
- if a charm name is indicated, will just list all libraries for that charm
In the store layer:
- a new multi-functional `get_libraries_tips` is added
- it's bulk, and supports all the flexibility in the store for each query:
- just the library id (will get the tip for that library)
- just the charm name (will get the tip for all libraries of that charm)
- charm and library names (alternative identification of a specific library)
- for any of those cases, `api` is supported (it will give the tip for that API version)
- note that this …
=> (charmlibs) List libraries for a given charm

charmcraft/templates/init/requirements-dev.txt.j2, charmcraft/templates/init/run_tests.j2, requirements-dev.txt
I think it'd be nice to include a coverage report in the default unit test output from what's generated by 'charmcraft init'. This PR adds that.
=> Add coverage to unit tests by default in 'charmcraft init'

completion.bash
The sad thing is that there's no possible to add a test that checks that we forgot to update this file after adding a new command...
=> Modernize the Bash completion definition.

charmcraft/cmdbase.py, charmcraft/commands/init.py, charmcraft/commands/pack.py, charmcraft/main.py, tests/commands/test_init.py, tests/commands/test_pack.py, tests/commands/test_store_commands.py, tests/commands/test_version.py, tests/conftest.py, tests/test_cmdbase.py, tests/test_help.py
Now the main module passes the config to all the commands.
The branch is a little too big, but most of the diff are mechanical changes (as most of the commands don't use the config, at least so far).
But there are two commands that are impacted by this change:
- `pack`: which previously loaded/validated the `charmcraft.yaml` file itself, now it just uses the config.
- `init`: which had a parameter to identify the project dir, and now this parameter is global to all the system.
=> Pass the config to all commands.

charmcraft/helptexts.py, tests/test_help.py
=> Mandatory parameters must be between angular brackets in the command's help.

charmcraft/commands/pack.py, charmcraft/commands/store/client.py, charmcraft/commands/store/store.py, charmcraft/config.py, tests/commands/test_pack.py, tests/commands/test_store_api.py, tests/commands/test_store_client.py, tests/test_config.py
Note: I had to change the behaviour when the `charmcraft.yaml` file is missing (so far is optional, in the future will be mandatory): previously in that case the whole config was None, but this way the Store URLs wouldn't get to the Store client, or the project directory wouldn't get to the `init` command.
Now the config object will always be there and useful, but with `type` in None. This is fine because the only ones using `type` are the bundle related commands (only `pack` so far, the next coming in the following days), for which the config is also mandatory. 
So if there is no charmcraft.yaml file at all the  config is created and passed around for all objects just fine and `pack` detects that config.type is None, so it complains that config is mandatory (like before).
In the future …
=> Make the Store client to use the Config (with production default URLs now).

charmcraft/commands/store/client.py, tests/commands/test_store_client.py
Extend the current user-agent to include the current system, machine
arch and python version, using conventions from the MDN docs. The
user-agent test has been updated to mock these values though it is a bit
ugly to do so, I don't exactly like the patching of `platform` so there may
be a better/cleaner way to handle that.
Also update copyright dates in files modified.
`459 passed, 8 warnings in 5.12s`
fixes #74
Happy to rework this however is desired!
=> improve the user-agent string sent to servers

charmcraft/cmdbase.py, charmcraft/commands/pack.py, charmcraft/config.py, charmcraft/main.py, tests/commands/test_pack.py, tests/test_config.py, tests/test_main.py
This is because it will be mandatory for the more building-related commands, but not for the more store-related ones.
So, now:
- each command indicates if config is mandatory for it, the infrastructure will check that, so the for the command is safe to assume it's always there (see change in `pack.py`).
- if the config was provided by the user is now an attribute of the Project in config, so the infrastructure (at least) can check it.
- if the config is provided, it's verified with the schema; otherwise everything is bootstrapped by default.
- `type` is back to mandatory if the config is provided.
=> Fix infrastructure around the concept that the config is not always mandatory.

charmcraft/commands/store/__init__.py, charmcraft/commands/store/store.py, charmcraft/main.py, completion.bash, tests/commands/test_store_api.py, tests/commands/test_store_commands.py
Also took the opportunity for a couple of small improvements:
- empty line after commands help text is superfluous (the formatter takes care of that, so I changed those that were inconsistent)
- a `meta` was redundantly used in a argparse option
=> Handling names for bundles: register (new command) and list (generalized previous one).

charmcraft/commands/store/__init__.py, charmcraft/utils.py, tests/commands/test_store_commands.py, tests/test_utils.py
=> Support for bundles in the Upload command.

charmcraft/commands/store/__init__.py, charmcraft/utils.py, tests/commands/test_store_commands.py, tests/test_utils.py
Explained changes (UX changes accoording to [this doc](https://docs.google.com/document/d/1dqzoFLEaB_1N_jJJdmsoCxeLUtTZRakveXF8aHx6lFA/)):
- `revisions` and `status`: now `name` is mandatory (no longer guessed from metadata)
- `release` now gets `name` as first mandatory parameter, then `--revision` as a mandatory option (only one allowed!) and `--channel` as mandatory option (multiple allowed).
=> Final commands changes for Bundles support.

charmcraft/templates/init/src/charm.py.j2
So I have recently worked on creating a new charm [operator for Redis](https://github.com/edumucelli/redis-operator). As someone new to Juju and with some knowledge on K8s I ended up struggling a bit to find where were the documentation, examples and even how to set up my local environment to make things work. Consider it as someone new to the whole context: I even searched for the instructions as someone from the outside, looking on Google for documentation -- which mostly took me to the reactive operator.
@mthaddon took some time today to discuss with me and gather some feedback about how the process was to understand where things were easy and where the main roadblocks were. One thing I have mentioned is that the skeleton command `charmcraft init` was great to give something that was …
=> Add init documentation for a gentle introduction to the charm operator

charmcraft/templates/init/src/charm.py.j2
This addresses https://github.com/canonical/charmcraft/issues/267 by adding a call to set the status in the init template for the charm.
=> Set unit status in default charm

charmcraft/commands/store/__init__.py, tests/commands/test_store_commands.py, tests/factory.py
Using '-' in a name means that the charmlib will have an un-importable path.
Mutate that to '_', and use that in places where we need to. This can be reversed from the filepath as '_' is not valid in a charm name (via https://juju.is/docs/charm-metadata )
Closes #265
=> Mutate - to _ to make importable names

charmcraft/templates/init/run_tests.j2
If you added a library to your charm, the tests would not run as it is not in the PYTHONPATH provided by the `run_tests` script.
Add it, so that tests will run.
=> Add lib path to run_tests template

charmcraft/commands/store/__init__.py, tests/commands/test_store_commands.py
This includes a small glitch when showing in a channel without resources in `status`, and a total refactor of the resources list, which now looks like:
```
$ fades -r requirements.txt -m charmcraft resources my-super-charm
Charm Rev    Resource      Type    Optional
17           showandtell   file    True
14           someresource  file    True
13           someresource  file    True
12           otherstuff    file    True
testresource  file    True
10           otherstuff    file    True
testresource  file    True
9            otherstuff    file    True
testresource  file    True
6            otherstuff    file    True
testresource  file    True
```
=> Improve the way to show resources.

charmcraft/commands/store/__init__.py, charmcraft/commands/store/store.py, tests/commands/test_store_api.py, tests/commands/test_store_commands.py
This is because the API changed, specifying the type for files is optional (for now), but we will need it soon to indicate oci-image types.
Also fixed/improved two help-related details in other commands.
=> Specify the resource type when uploading one.

charmcraft/templates/charmlibs/new_library.py.j2
`charmcraft push-lib` doesn't seem to exist currently, update the template to use the correct command.
=> Update charm library template for correct command to publish or update libraries

charmcraft/utils.py, tests/test_utils.py
This is temporary, these new translations will be removed when we get into a classic snap.
Also changed the name to com from the 'id' from os_release file.
=> Better manifest in case of strict snap.

.gitignore
=> gitignore: ignore .envrc for direnv users

snap/snapcraft.yaml
Classic snaps on core20 require python3.  Add this collection
of stage packages as its own part to separate stage filtering
used in the charmcraft part.
There is an apparent bug in Snacpraft where it will set the
bin/python3 to an invalid symlink in this scenario.  Hardcode
the correct symlink until we have a fix in place for Snapcraft.
=> snap: strict -> classic confinement for Charmcraft snap

snap/snapcraft.yaml
=> snap: explicitly use requirements.txt for dependencies

snap/snapcraft.yaml
- Plugs are not allowed for classic, remove.
- Some python packages don't have wheels for architectures other
than amd64.  Add python3-dev package to build from source,
and provide CPPFLAGS/LDFLAGS to indicate where to find them,
rather than looking for them in stage.
=> snap: remove plugs and add python3-dev build-package

charmcraft/commands/store/registry.py, tests/commands/test_store_registry.py
The previous error was a mess in the CLI; now the info is just logged and the message is nicer.
=> Improved the message for the case of Dockerhub not having v2 manifests.

charmcraft/config.py, tests/test_config.py
Add support `bases:` keyword, targetting only the long-form.
Short-form support will be added later.
=> config: introduce long-form bases support

charmcraft/config.py, charmcraft/deprecations.py, tests/test_config.py, tests/test_deprecations.py
Added `registry-url` to the configuration, in preparation for the resources refactor.
Also changed the other `charmhub` keys to use dash, instead of underscore. But to do that change, I included some deprecation infrastructure.
I thought about preparing a branch with the deprecation infra alone, but I took the opportunity of being able to include it here (not too many lines) as it shows also how that infra is used.
=> New config, and deprecation infrastructure

charmcraft/commands/store/__init__.py, charmcraft/commands/store/registry.py, tests/commands/test_store_commands.py, tests/commands/test_store_registry.py
This is to align the classes' signatures for the big refactor ahead.
Specifically, in OCIRegistry:
- receive just the image name (whatever it could be) and not the two "orga" and "name" parameters which were too specific for image names with only two "tokens"
- also receive username and password, and store the ready-to-use encoded credentials
- changed slightly a couple of url-massaging functions to reflect the fact that the server has now the schema in it (not faking it anymore, more robust)
And in ImageHandler:
- receive now just the registry and use it
- it will hold only one registry now, so now need for the "dst_" prefix
Also in the upload-command command, changed from passing the components to just pass the registry itself.
Note I minimized the changes in the tests; some of those …
=> Refactor how OCIRegistry and ImageHandler are used (CRAFT-53)

tests/commands/test_store_registry.py, tests/test_main.py
Some small changes, everything just in tests, no affected functionality:
- simplified some OCIRegistry calls, the "test-orga" makes no more sense (left it as-is in other tests that will disappear in the future)
- improved some test names
- added schema to "service" key in auth tests, it's more real now
- improved a test in test_main.py to isolate it from the running environment
=> Tests improvements to minimize future merges from resources draft branch

charmcraft/commands/store/registry.py, tests/commands/test_store_registry.py
I introduced here a FakeRegistry helper that has more functionality than what's strictly needed for *this* branch, but will be used in the next ones (in the end, this is to simplify mergings).
=> Added small functionality to verify if an image exists in the Registry. (CRAFT-235)

charmcraft/commands/build.py, charmcraft/commands/pack.py, charmcraft/manifest.py, charmcraft/utils.py, tests/test_manifest.py, tests/test_utils.py
- Move create_manifest() out of utils into its own module.  This will
prevent a potential import loop due to dependencies on util in config.
- Add optional bases_config parameter to use the run-on bases
configuration.
Note that runtime usage still only invokes the "legacy" non-bases
configuration.  Future work will enable the usage of bases and this
just adds test coverage for the future case.
=> manifest: add bases support to create_manifest() (CRAFT-63)

charmcraft/commands/build.py, tests/commands/test_build.py
Maintain current format as "legacy" until we have the (default) bases
configuration available in upcoming PRs. Note that only the legacy
path is utilized at runtime, with tests added for bases configuration
support.
=> commands/build: charm file name format support for bases (CRAFT-66)

charmcraft/bases.py, charmcraft/commands/build.py, tests/commands/test_build.py, tests/test_bases.py
- Intoduce bases module with `get_host_as_base()` and
`check_if_base_matches_host()`.
- Extend build/pack to support `bases` configuration if present
and managed-mode is enabled.  Error if unable to build for any of
the configured bases.  Warn for each bases config that cannot be
built for.  Provide additional debug logging on matching behavior
to help diagnose matching issues when they occur.
- Update run() to return a list of charms built rather than just
the charm file name.
Note bases are currently required with the use of managed mode until
we introduce the default bases configuration.
=> build/pack: add support for bases in managed mode (CRAFT-131)

charmcraft/commands/store/__init__.py, completion.bash, tests/commands/test_store_commands.py
Now it will stop using Dockerhub, and the process will be:
- check if the indicated digest is in Canonical's registry; if yes, use it
- else try to upload it; the ImageHandler function will upload it and will return the new remote digest, in which case it will be used, or None, in which case an error will be presented to the user
Once the command has the image's digest from the Canonical's Registry (because it was already there, or just uploaded), will request the formal JSON to Charmhub, which will be uploaded back to Charmhub as any other resource.
=> Refactored the upload-resource command for it's new behaviour (CRAFT-240)

charmcraft/logsetup.py
Enable logging for craft-providers library, matching the current
logging behaviors for charmcraft.  Add 'enabled_loggers' list to
support doing this in an easily extensible manner.
Example log snippet when running with --verbose:
```
2021-06-17 11:24:46,538  charmcraft                     DEBUG    Starting charmcraft version 0.10.0+199.g6541d0a.dirty
2021-06-17 11:24:46,538  charmcraft.main                DEBUG    Raw pre-parsed sysargs: args={'help': False, 'verbose': True, 'quiet': False, 'project_dir': None} filtered=['pack']
2021-06-17 11:24:46,539  charmcraft.main                DEBUG    General parsed sysargs: command='pack' args=[]
2021-06-17 11:24:46,540  charmcraft.main                DEBUG    Command parsed sysargs: Namespace(entrypoint=None, requirement=None, debug=False, …
```
=> logsetup: enable logging for craft-providers (CRAFT-149)

charmcraft/commands/build.py, charmcraft/commands/pack.py, tests/commands/test_build.py, tests/commands/test_pack.py
Allow the user to specify --bases-index <index> to limit the targets
being built.  Pass this through pack's run() so we don't have to
further extend the deprecated pack's arguments.
These indices are validated at runtime because the current Validator
does not have the config available to validate against.
=> pack: introduce support for --bases-index to specify targets (CRAFT-148)

charmcraft/config.py, charmcraft/env.py, tests/test_config.py, tests/test_env.py
Add get_managed_environment_project_path() to get managed directory
path.  When in managed-mode, default to it.  Note that it could still
be overwritten by using --project-dir.
=> config: default path to /root/project when in managed mode (CRAFT-300)

charmcraft/providers.py, requirements-dev.txt, requirements.txt, setup.py, snap/snapcraft.yaml, tests/test_providers.py
- Add craft-providers dependency (version will be updated in
future work) to project & snap.
- Add CharmcraftBuilddBaseConfiguration which extends the buildd
image configuration with the setup code to:
- install python3-pip
- install python3-setuptools (required explicitly for 18.04)
- install the Charmcraft snap by injecting the host's, which
should be OK as the snap is currently required.  Future work
could extend this to add a fallback to install from store using
snap_installer.install_from_store().  Note that this injection
is unconditional, future work will add a check to see if the
injection is necessary prior to doing it (that is, don't inject
if reusing an instance that has the correct version already).
=> providers: introduce charmcraft base configuration (CRAFT-261)

charmcraft/providers.py, tests/test_providers.py
Initial support for provided environments includes:
- Ubuntu 18.04
- Ubuntu 20.04
The host architecture must be included in the base's architectures,
which may change in the future when LXD clusters are supported with
multiple architectures.
Add is_base_providable() interface to perform this check and add
BASE_CHANNEL_TO_BUILDD_IMAGE_ALIAS to track supported channel ->
alias mappings.
=> providers: constrain buildable environments (CRAFT-263)

charmcraft/commands/build.py, charmcraft/config.py, charmcraft/metadata.py, tests/commands/test_build.py, tests/test_metadata.py
Move metadata logic into its own module, migrating to pydantic
and re-using bits found for charmcraft.yaml config parser.
This will allow for re-use of metadata for commands other than
build/pack.
=> metadata: refactor parsing into own module (CRAFT-311)

charmcraft/providers.py, tests/test_providers.py
Add get_command_environment() method to build and return the command
environment to use when executing commands in the provided container.
Starting with the default buildd environment, add:
- CHARMCRAFT_MANAGED_MODE=1
- [http|https|no]_proxy settings if found in current Charmcraft process.
=> providers: introduce get_command_environment() to build env (CRAFT-262)

charmcraft/providers.py, tests/test_providers.py
Launch lxc container and configure for use with charmcraft,
adding/configuring the buildd remote as necessary.
=> providers: introduce launch_environment() (CRAFT-312)

charmcraft/commands/store/__init__.py, tests/commands/test_store_commands.py
Note about some `all_tracks`-related code deletion: we're now Python 3.6+, so we can rely on dict's order.
Fixes #129.
=> Added bases column in the `status` command output (CRAFT-299).

charmcraft/providers.py, tests/test_providers.py
Provide interface for upcoming 'clean' command to clean all
environments created for a given project.
=> providers: introduce clean_project_environments() (CRAFT-314)

charmcraft/commands/build.py, tests/commands/test_build.py
For each bases configuration, check if a build-on base can be
provided.  If so, launch environment and execute pack command
inside each to build charm for each viable bases config index.
Future work should extend the pack command to include the parent's
verbose or quiet mode flags for consistency.
=> build: pack charm in provided environment when using bases (CRAFT-313)

.github/workflows/tests.yaml, charmcraft/commands/build.py, charmcraft/commands/pack.py, charmcraft/config.py, charmcraft/deprecations.py, charmcraft/manifest.py, requirements-dev.txt, requirements.txt, tests/commands/test_build.py, tests/conftest.py, tests/test_config.py, tests/test_deprecations.py, tests/test_manifest.py
Set the default bases configuration to Ubuntu 20.04 for the host's
architecture.  This will effectively end legacy builds.
Add DN02 to deprecate projects without charmcraft.yaml.
Add DN03 to deprecate projects with bases configuration.
Add reset_deprecation_notices() autouse fixture to reset global value
found in deprecations module.
=> config/build: set default bases configuration with DNs (CRAFT-265, CRAFT-266)

charmcraft/commands/init.py, charmcraft/templates/init/charmcraft.yaml.j2, tests/commands/test_init.py
Initialize charmcraft.yaml with type "charm" and an Ubuntu 20.04
bases configuration.
=> init command: populate default charmcraft.yaml (CRAFT-330)

charmcraft/commands/build.py, charmcraft/logsetup.py, tests/commands/test_build.py, tests/test_logsetup.py
When building with provided (managed) instance, append --verbose
or --quiet as required to match the parameter given to the host
charmcraft instance.
=> build/pack: pass --verbose or --quiet as needed (CRAFT-322)

charmcraft/commands/build.py, charmcraft/env.py, charmcraft/logsetup.py, charmcraft/providers.py, tests/commands/test_build.py, tests/test_env.py, tests/test_providers.py
Catch error when failing to pack a Charm, retrieving the logs from
the managed instance for easier inspection by the user.
- Update logger to write to /tmp/charmcraft.log so that it can be
readily retrieved by the host Charmcraft instance.  Provide this
path with a new env.get_managed_environment_log_path() interface.
Additionally, ensure the log file is truncated with mode='w' so
the instance logs are only for the last run.
- prefix logs in managed instance with "mm "
- add providers.capture_logs_from_instance() to providers to retrieve
logs and send them to logger.debug()
- update build to use this mechanism
=> pack: fetch logs from managed instance on error (CRAFT-333)

charmcraft/commands/clean.py, charmcraft/providers.py, tests/commands/test_clean.py, tests/test_providers.py
If Charmcraft were to build the same project [name] simultaneously in
two different directories, collisions on the containers in use may
occur.
To account for this, this PR uses the project directory's inode in the
container name.  This will ensure uniqueness for projects in multiple
paths, but also seamlessly handle project directory moves that don't
cross the filesystem boundary, the common case.
Note that 'clean' command will not affect other project directories,
so the clean must occur in the original directory.  To handle any
potentially unassociated containers, future work will include more
sweeping purge capabilities for the clean command.  This is not unique
to the introduction of the use of the directory inode, but is
exacerbated by it.
Signed-off-by: Chris Patterson …
=> providers: account for project path in instance name (CRAFT-334)

charmcraft/providers.py, tests/test_providers.py
If the managed instance never gets to creating the log, for whatever
reason, catch the FileNotFoundError and log it.
=> providers: handle unexpected case where instance never logs (CRAFT-345)

charmcraft/providers.py, tests/test_providers.py
Git may be required to install python dependencies for projects.
Instead of using git from the snap, install the native git on
the host as a required dependency.  Future work on craft-parts
may aborb this dependency.
=> providers: install git as required dependency (CRAFT-346)

charmcraft/commands/build.py, tests/commands/test_build.py
This information was being logged to debug, but should be made
available to user regardless if erroring out.  Log it as informational.
Also tweak the language to be more generic rather than intended
for managed/destructive mode (host isn't matched for provided
environments).
=> build: log reason to ignore build-on entry to info (CRAFT-350)

charmcraft/commands/build.py, tests/commands/test_build.py
Let the user know which charm is being packed and that it may take some
time.  Move launched_environment() logic into pack_charm_in_instance()
to have the information required (charm name) prior to launching.
Example output:
```
$ charmcraft pack
Packing charm 'foo_ubuntu-18.04-amd64.charm' which may take several minutes...
Created 'foo_ubuntu-18.04-amd64.charm'.
Packing charm 'foo_ubuntu-20.04-amd64.charm' which may take several minutes...
Created 'foo_ubuntu-20.04-amd64.charm'.
```
=> build: inform user that packing charm may take time (CRAFT-347)

charmcraft/providers.py, tests/test_providers.py
Python complains when wheel is not installed, install it in the
target instance as a build dependency.
=> providers: add python3-wheel as dependency (CRAFT-351)

CONTRIBUTING.md, README.md, charmcraft/commands/init.py, charmcraft/templates/init/CONTRIBUTING.md.j2, charmcraft/templates/init/README.md.j2, charmcraft/templates/init/metadata.yaml.j2, tests/commands/test_init.py
Include examples of more relation possibilities in `metadata.yaml`, and avoid using hyphens for them in favor of underscores. Also add `display_name`
Split developer contributing instructions to a separate document so the published README doesn't have them.
Also, update the README for charmcraft itself so contributors don't have to read the source to find out why `python -m charmcraft` doesn't actually work when cloned from git
=> Update the default bundle from `charmcraft init`

.github/workflows/tests.yaml, charmcraft/commands/build.py, charmcraft/env.py, tests/commands/test_build.py, tests/test_env.py
If building in project directory, use the project path as the working
directory. The output charms will be placed in the correct directory
without needing retrieval. If outputing to a directory other than the
charm project directory, we need to output the charm outside the
project directory and can retrieve it when complete. Use the home
directory for this output inside the container.
=> commands/build: output charms to cwd when using provider (CRAFT-359)

.github/workflows/tests.yaml, charmcraft/commands/build.py, charmcraft/commands/pack.py, tests/commands/test_build.py, tests/commands/test_pack.py
- Add --destructive-mode bool parameter to pack command.
- Add basic_project_builder fixture for reusable project building
code to help reduce further duplication.
- Update Builder.run() with parameter to indicate whether or not
to build in destructive-mode.  Use it when determining how to
appropriate build/pack charm(s).  Behavior is consistent with
managed-mode.
=> commands/pack: add --destructive-mode support (CRAFT-358)

charmcraft/commands/build.py, charmcraft/commands/pack.py, charmcraft/config.py, charmcraft/linters.py, charmcraft/manifest.py, tests/commands/test_build.py, tests/test_linters.py, tests/test_manifest.py
Call linters' analyze from build command and deal with the results: so far only log the attribute ones (in the future it will deal also with warnings and errors), and use them for the manifest creation. Also changed the manifest creation function to properly save this new info.
Note: I had to fix checkers/analyze to save information in the shared state (a checkers integration test was missing).
Note 2: This PR depends on #443.
=> Use linters' analyze from build command (CRAFT-318)

charmcraft/env.py, tests/test_env.py
=> env: use new setting-up-charmcraft page for installation URL (CRAFT-273)

charmcraft/linters.py, tests/test_linters.py
The text and url attributes, even if they get dinamic, need to be safe values, as they may be accessed without running the checker (when ignored) or even after crashing.
Beyond providing a specific test case for the change, I made explicit the attributes access for those situations in other tests.
=> Ensure all checkers have usable text and url.

.github/workflows/tests.yaml, charmcraft/commands/build.py, charmcraft/commands/pack.py, charmcraft/config.py, charmcraft/logsetup.py, charmcraft/main.py, charmcraft/manifest.py, charmcraft/parts.py, charmcraft/providers.py, requirements-bionic.txt, requirements-dev.txt, requirements-focal.txt, requirements.txt, setup.py, snap/snapcraft.yaml, tests/commands/test_build.py, tests/commands/test_pack.py, tests/conftest.py, tests/test_config.py, tests/test_manifest.py, tests/test_parts.py, tests/test_providers.py, tools/freeze-requirements.sh
Create and run the craft-parts lifecycle, executing the charm builder
from a craft-parts charm build plugin.
=> build: integrate craft-parts lifecycle (CRAFT-89, CRAFT-367, CRAFT-357)

.github/workflows/tests.yaml, charmcraft/commands/build.py, charmcraft/commands/pack.py, charmcraft/deprecations.py, charmcraft/parts.py, requirements-dev.txt, requirements.txt, setup.py, tests/commands/test_build.py, tests/test_parts.py, tools/freeze-requirements.sh
The charm entry point and charm requirements can now be set using
charm plugin properties. Deprecation notices have been added to the
`--entrypoint` and `--requirement` command line arguments. An error is
issued if both sources of information are used at the same time.
=> parts: add entrypoint and requirements properties to charm plugin (CRAFT-393)

charmcraft/config.py, charmcraft/parts.py
Add charm configuration documentation to the configuration schema.
=> config: add charm part to documentation (CRAFT-356)

charmcraft/commands/build.py, tests/commands/test_build.py
The command line switch to set requirements was deprecated in favor of
using the `charm-requirements` property in the charm part. Test it
instead of the command line variable.
=> build: prime venv if charm-requirements defined (CRAFT-417)

charmcraft/providers.py, requirements-dev.txt, requirements.txt, tests/test_providers.py
Invoke ensure_lxd_is_ready() interface before using LXD
provider. This consolidates a couple of existing checks
done elsewhere as well as a new one for ensuring the user
has the necessary permissions to use LXD.
Minor simplification of imports used in providers module
to improve and update mocks accordingly.
Example error:
```
$ /snap/bin/charmcraft pack
LXD requires additional permissions.
Please ensure that the user is in the 'lxd' group.
(full execution logs in '/home/test1/snap/charmcraft/common/charmcraft-log-0xgcist7')
```
=> charmcraft: perform LXD checks before use (CRAFT-420)

charmcraft/commands/build.py, tests/commands/test_build.py
Add `LICENSE` and `icon.svg` to the list of files to be included in
the charm, if they exist in the project directory.
=> build: include optional license and icon files (CRAFT-436)

charmcraft/utils.py, setup.py
This removes attr usage in Charmcraft, so remove attrs
from install_requires as well.  Does not affect the generated
requirements as other dependencies require attrs anyhow.
=> utils: use dataclass for ResourceOption

.github/workflows/tests.yaml, charmcraft/snap.py, requirements-dev.txt, requirements.txt, setup.py, snap/hooks/configure, snap/snapcraft.yaml, tests/test_snap.py
Enable (unused) configuration for 'provider', erroring if set to
anything other than multipass or lxd.  Update requirements
to include snap-helpers.
Example error:
```
$ snap set charmcraft provider=invalid
error: cannot perform the following tasks:
- Run configure hook of "charmcraft" snap (run hook "configure":
Invalid snap configuration: provider 'invalid' is not supported.)
```
=> snap: add configure hook with support for provider (CRAFT-363)

charmcraft/commands/build.py, tests/commands/test_build.py
The README.md file is used by CharmHub to display the contents of the
charm's page. This file should then be included by default.
=> build: add README.md by default

tests/commands/test_build.py
Upcoming additions to Builder options will make it increasingly
difficult to add new options.  Add a get_builder() interface
to construct Builder with the defaults, allowing for overrides
to handle the necessary test cases.
=> tests: refactor Builder instantiation for build module (CRAFT-407)

.github/workflows/tests.yaml, charmcraft/commands/build.py, charmcraft/providers/__init__.py, charmcraft/providers/_get_provider.py, charmcraft/providers/_multipass.py, requirements-dev.txt, requirements.txt, tests/commands/test_build.py, tests/providers/test_get_provider.py, tests/providers/test_multipass.py
Add support for Multipass similar to LXD.
To determine provider on linux:
- check CHARMCRAFT_PROVIDER environment variable if in
developer mode.
- check snap configuration if running as snap.
- fall back to platform default.
Update execute_run() to use cwd=pathlib.Path(x) interface.
Add unit tests and a smoke test for Linux & Multipass.
=> providers: introduce multipass support (CRAFT-409)

.github/workflows/tests.yaml, charmcraft/commands/build.py, tests/commands/test_build.py
When building in managed mode use workdir outside of project dir to
prevent leaks to the external environment.
=> build: fix parts workdir in managed mode (CRAFT-459)

charmcraft/commands/build.py, tests/commands/test_build.py
Determine bases that can be built first (in new `plan()` method)
then run through the process of building.
=> commands/build: separate planning from execution (CRAFT-331)

charmcraft/providers/_lxd.py, charmcraft/providers/_multipass.py, tests/providers/test_lxd.py, tests/providers/test_multipass.py
- Ensure there is error handling for all provider-generated
exceptions. Catch BaseConfigurationError when launching
environments for LXD and Multipass and add missing try/except
cases in LXD provider.
- Ensure all exceptions are chained (and make sure the tests
validate it)
- Add test coverage for added exception handling.
=> providers: improve error handling (CRAFT-472)

charmcraft/config.py, tests/test_config.py
I just fixed this when loading the config, so at least `charmcraft` does not crash.
I considered doing this verification in `main.py`, when loading the argument. The verification there would make more sense, as it's a "command line argument" verification, and we could raise a proper ArgumentParsingError indicating that the directory does not exist.
However, we *may want* for `--project-dir` to point to a directory that is not there, for the `init` command. See issue #198, where it claims that if the directory indicated to `init` is not there, we should create it.
So, in the end, I decided that the best behaviour is to just "accept" the parameter pointing to nowhere, and load a default config with that info. Note that the flag `config_provided` is `False` in this case, so if the executed …
=> Support --project-dir pointing to a missing directory (CRAFT-474).

charmcraft/commands/store/client.py
os.fchmod() is not supported on Windows.  Howver, the permissions
are already set on open(), we do not need to set them again.
=> store/client: skip unneeded fchmod (CRAFT-497)

charmcraft/utils.py, tests/test_utils.py
=> utils: add arch translation for Windows' AMD64 (CRAFT-499)

setup.py
On Windows we get an error when using rename to overwrite an existing
file:
FileExistsError: [WinError 183] Cannot create a file when that file
already exists: 'charmcraft\\version.py~' -> 'charmcraft\\version.py'
Unlink the target first if it exists.
=> setup: unlink target file before rename (CRAFT-495)

charmcraft/env.py, tests/test_env.py
Add a platform check for Linux before vetting that Charmcraft is
running from the snap (or running in developer mode).
=> env: add win32 to supported platform environments (CRAFT-498)

charmcraft/logsetup.py, tests/test_logsetup.py
Attempting to unlink the open file on Windows results in:
PermissionError: [WinError 32] The process cannot access the file because it is
being used by another process.
Save off the file handle and close it before unlinking.
=> logsetup: close log descriptor before unlinking (CRAFT-503)

charmcraft/charm_builder.py, charmcraft/commands/init.py
Windows does not support executable bits or fchmod().  Check if
system is posix before setting exe bit.
=> make required files executable (CRAFT-501)

charmcraft/env.py, charmcraft/providers/_buildd.py, tests/providers/test_buildd.py, tests/test_env.py
On Linux, the default behavior is to inject the host snap into the target
environment.
On other platforms, the Charmcraft snap is installed from the Snap Store.
When installing the snap from the Store, we check if the user specifies a
channel, using CHARMCRAFT_INSTALL_SNAP_CHANNEL=<channel>.  If unspecified,
we use the default determined by get_managed_environment_snap_channel_default().
On Linux, the user may specify this environment variable to force Charmcraft
to install the snap from the Store rather than inject the host snap.
=> providers: add support to install Charmcraft snap from store (CRAFT-502)

charmcraft/commands/init.py, tests/commands/test_init.py
Future work can add similar support for other platforms. Example
code for Windows:
https://sjohannes.wordpress.com/2010/06/19/win32-python-getting-users-display-name-using-ctypes/
=> commands/init: fix handling for platforms without pwd (CRAFT-496)

.github/workflows/tests.yaml, tests/commands/test_analyze.py, tests/commands/test_build.py, tests/commands/test_pack.py, tests/commands/test_store_client.py, tests/commands/test_store_commands.py, tests/commands/test_store_registry.py, tests/test_charm_builder.py, tests/test_config.py, tests/test_infra.py, tests/test_jujuignore.py, tests/test_linters.py, tests/test_parts.py, tests/test_utils.py
As a starting point for Windows testing, we disable all tests which fail
on Windows.  Over time we should update the tests to either work on
Windows, or mark them as specifically unsupported on Windows.
Tests are disabled entirely for the test_parts module, as craft-parts
does not yet support Windows.  In practice in may not be much effort
to enable it for these tests.
The rest of the tests are disabled on a per-test basis.
=> tests: skip broken tests when running on Windows (CRAFT-504)

charmcraft/helptexts.py, charmcraft/main.py, tests/test_help.py, tests/test_main.py
This includes:
- not having the general summary or app name anymore hardcoded in the module
- moved the functions at module level to be methods inside a class; this is for the system to be able to be "initiated" with the app specific information. 
- those moved in functions are exactly the same, with some minor structural changes:
- `get_full_help` and `get_detailed_help` do not receive the "command groups" 
- `get_usage_message` now formats `USAGE` passing also the `appname`
- `get_full_help` and `get_detailed_help` indents the "general summary" (as the app text doesn't need to be passed indented)
**Note** on initiating `Helper`: currently there's no guard on using it before calling its `init`, as I'm not 100% sure the form this will have when both this help texts module and the …
=> First step in isolating the help texts module from the app itself (CRAFT-530).

charmcraft/parts.py, requirements-dev.txt, requirements.txt
Update dependencies to require Craft-parts 1.0.1 and remove refreshing
of stage packages (Craft-parts now uses the host state for apt cache).
Time comparison for non-parallel execution of regression tests:
* with Craft-parts 1.0.0: `81.14user 15.46system 1:30.80elapsed`
* with Craft-parts 1.0.1: `41.76user 3.97system 0:37.82elapsed`
=> requirements: update craft-parts to 1.0.1 (CRAFT-430, CRAFT-520)

charmcraft/env.py, tests/test_env.py
It has the same mechanics as Windows but with much more similarities
at the platform level to Linux.
=> env: enable darwin (CRAFT-535)

.github/workflows/tests.yaml
LXD is preinstalled on the 20.04 images, it can still work without
refreshing to the latest.
=> tests: warn if LXD cannot be refresh in 20.04's GHA

charmcraft/helptexts.py, charmcraft/main.py, tests/test_cmdbase.py, tests/test_help.py
In detail:
- Stop passing (again) the application name when calling `get_usage_message`
- Moved two tests from "help suite" to "cmdbase suite" as they were more about the command's content than the help infrastructure
- Fixed/improved tests so they don't depend anymore on `COMMAND_GROUPS` nor `VersionCommand`, which are app-specific
=> More isolation of the helptext module and simplification of its usage (CRAFT-528)

.github/workflows/tests.yaml, charmcraft/charm_builder.py, charmcraft/parts.py, requirements-dev.txt, requirements.txt, tests/test_charm_builder.py, tests/test_parts.py
Comply with the requirement of not installing binary dependencies,
building them locally instead. The process may take a long time to
complete, so use the venv module to install requirements to a persistent
staging virtualenv so that dependencies already installed won't be
reinstalled (and rebuilt) when the charm is repacked.
Note: This solution installs additional dependencies to venv
(setup-tools, pip, and pkg_resources).
=> charm_builder: build dependencies locally (CRAFT-537)

charmcraft/config.py, tests/test_config.py
=> For bundles, do not show a deprecation message if 'bases' not included, and forbid its usage.

.github/workflows/tests.yaml, charmcraft/charm_builder.py, charmcraft/parts.py, tests/test_charm_builder.py, tests/test_parts.py
Packages listed in the `charm-python-packages` property are installed
before dependencies listed in the requirements file. This mirrors
`python-packages` that exists in the python plugin.
=> parts,charm_builder: add charm-python-packages plugin property (CRAFT-552)

tests/test_main.py
The main benefit here is that the test execution (which is kind of slow for each command) can be parallelized now.
=> Converted the sanity command test from using a loop to be parametrized.

charmcraft/helptexts.py, charmcraft/main.py, tests/test_cmdbase.py, tests/test_help.py, tests/test_infra.py, tests/test_main.py
This is a requirement for when the command groups will be defined and used by different codes (lib and app), after the split of part of `charmcraft` code to `craft-cli`.
While doing this, I also removed the group's "codename" and just left the "description", which is what should be used for showing to the user.
=> Formalize the command groups to be proper objects, not a tuple of values (CRAFT-560).

charmcraft/main.py, tests/test_main.py
This is a small improvement (the dispatcher supporting the "extra global args", for which tests were added) and two groups of code moved around (no tests changes needed, as there is no functionality changes really). All part of the plan of splitting this functionality into `craft-cli` lib.
The code moved around or changed is:
- better names! `_Global` transformed into `GlobalArgument` as this will be part of the lib's public API, and `GLOBAL_ARGS` transformed into `_DEFAULT_GLOBAL_ARGS` which will be part of the internal lib's functionality
- moved the functionality of three help-related functions to be part of the Dispatcher (as they need to access/use the "final global args")
Note that the "project dir" global arg is still "default", but will be moved to be "extra" when the Dispatcher …
=> Improved the Dispatcher to work with default global args and support extra ones in the future (CRAFT-565).

.github/workflows/tests.yaml
Fix for:
```
Run pip install -U pip wheel setuptools
Requirement already satisfied: pip in c:\hostedtoolcache\windows\python\3.8.10\x64\lib\site-packages (21.2.4)
Collecting pip
Downloading pip-21.3-py3-none-any.whl (1.7 MB)
Collecting wheel
Downloading wheel-0.37.0-py2.py3-none-any.whl (35 kB)
Requirement already satisfied: setuptools in c:\hostedtoolcache\windows\python\3.8.10\x64\lib\site-packages (56.0.0)
Collecting setuptools
Downloading setuptools-58.2.0-py3-none-any.whl (946 kB)
Installing collected packages: wheel, setuptools, pip
Attempting uninstall: setuptools
Found existing installation: setuptools 56.0.0
Uninstalling setuptools-56.0.0:
Successfully uninstalled setuptools-56.0.0
Attempting uninstall: pip
Found existing installation: pip 21.2.4
Uninstalling pip-21.2.4: …
```
=> github actions: don't upgrade pip on Windows

charmcraft/env.py, charmcraft/main.py, tests/test_env.py, tests/test_main.py
Keep the flag for use of other features, like switching providers, but
do not enforce it to allow for HOMEBREW Linux to work.
=> env: remove strict DEVELOPER environment (CRAFT-573)

charmcraft/commands/store/__init__.py, charmcraft/commands/store/client.py, charmcraft/commands/store/registry.py, charmcraft/parts.py, tests/commands/test_store_client.py, tests/commands/test_store_commands.py, tests/commands/test_store_registry.py, tests/test_parts.py
In detail:
- ensured that when the error comes from a sub-process, use `from err` (no need for another error type, it's just handled by `craft-cli`)
- started to use `details` attribute in some errors, to provide extra info
- returned 1 from commands that actually end ok (raising CommandError) but show error messages that come from an unsuccesful call to the Store
- support `craft-store` raising StoreServerError and transform that correctly
=> Revisited all error usage to adapt to new craft-cli context.

charmcraft/commands/build.py, charmcraft/commands/pack.py, charmcraft/config.py, charmcraft/parts.py, tests/commands/test_build.py, tests/commands/test_pack.py, tests/conftest.py, tests/test_config.py, tests/test_parts.py
The `charm` part is implicitly created in a charm project if no parts are specified by the user. If the toplevel `parts:` property is declared, the implicit part is not created. Do the same with the `bundle` part in bundle projects.
Fixes #590
**Note to reviewers**: tests for the following cases have been added to the charm and bundle building tests:
* No `parts` section defined
* `parts` section defined and `charm` or `bundle` part declared with additional files in `prime`.
* `parts` section defined without `charm` or `bundle` part declared. In the charm project case this can be used to create generic hooks-based charms.
* `parts` section defined and `charm` or `bundle` part declared with a non `charm` or `bundle` plugin.
=> build: don't create implicit part if parts section specified (CRAFT-633)

charmcraft/commands/store/__init__.py, charmcraft/commands/store/client.py, charmcraft/commands/store/store.py, requirements-dev.txt, requirements.txt, tests/commands/test_store_api.py, tests/commands/test_store_client.py, tests/commands/test_store_commands.py
For this I had to update the `craft-store` version, which implied a couple of unexpected API changes (very small, so I just left them here).
=> Show more information about current credentials in the whoami command (CRAFT-651).

.github/workflows/tests.yaml
To avoid regressions like the one described in https://github.com/canonical/charmcraft/issues/625, this adds a test where we build the prometheus-k8s-operator, which at the moment is the most complex charm of the observability team.
=> add prometheus charm pack test

charmcraft/charm_builder.py, charmcraft/commands/build.py
This will save ourselves from having an intermediate `sh` process for the duration of the hook's execution.
=> dispatch: Use exec to save an indermediate process

charmcraft/commands/build.py, charmcraft/jujuignore.py, tests/commands/test_build.py, tests/test_jujuignore.py
In detail:
- removed legacy support for bases configuration being None
- improved the message when launching container/VM (suggested by Mark)
- better logging of jujuignored rules
=> Several small improvements after testing and inspecting logs.

charmcraft/commands/store/__init__.py, charmcraft/commands/store/client.py, charmcraft/commands/store/store.py, requirements-dev.txt, requirements.txt, tests/commands/test_store_api.py, tests/commands/test_store_client.py, tests/commands/test_store_commands.py
- updated StoreClient init to use new parameters (without making use of them
yet)
- s/NotLoggedIn/CredentialsUnavailable/
- better support for missing Keyring scenarios
- adapted the relogin scenario to consider CredentialsAlreadyAvailable
=> craft store: update to 2.0.0 (CRAFT-773)

charmcraft/commands/store/__init__.py, tests/commands/test_store_commands.py
In some cases the name of the charm a user wants to upload is not the
same as the one specified in metadata.yaml. Specifically for charms
imported into charmhub from the old charmstore this isn't true if they
formerly namespaces (e.g. cs:~foo/bar become foo-bar but charm name
remains foo in metadata.yaml).
To allow charms to be still uploaded in this case a --name option is
added to the upload command which allows a user to specify the exact
name of the charm he wants to upload to rather than letting charmcraft
automatically extract the name from the metadata.yaml file
Fixes #681
=> Add name argument for upload command

charmcraft/commands/init.py
Before that fix, it was needed to look into the source code to identify the correct pattern.
=> improve "not a valid charm name" error

.github/workflows/tests.yaml, charmcraft/providers/_multipass.py, charmcraft/providers/_provider.py, tests/providers/test_multipass.py
=> multipass: use the correct image remote

.github/workflows/tests.yaml, charmcraft/parts.py, libexec/craftctl, requirements-dev.txt, requirements.txt, snap/snapcraft.yaml, tests/test_parts.py
Use craft-parts 1.4.0 with support to craftctl. Users can now invoke
`craftctl default` from part scriptlets to run the overriden step's
built-in handler.
---
CRAFT-944
=> parts: update craft-parts and enable craftctl

charmcraft/commands/store/__init__.py, charmcraft/utils.py, tests/commands/test_store_commands.py, tests/conftest.py, tests/test_utils.py
Also improved how errors are shown in the Emitter fixture.
Fixes #643 .
=> Show better timestamps in commands outputs (CRAFT-873).

charmcraft/commands/build.py, tests/commands/test_build.py, tests/test_infra.py
Took the opportunity to fix how flake8 issues were reported.
=> Pause the emitter while launching the user-requested shell (CRAFT-871).

charmcraft/commands/store/__init__.py
=> Re-use the file descriptor already opened by the tempfile to not leak it.

charmcraft/commands/store/__init__.py, charmcraft/commands/store/client.py, charmcraft/commands/store/store.py, requirements.txt, tests/commands/test_store_api.py, tests/commands/test_store_client.py, tests/commands/test_store_commands.py
This means no keyring issues
#730
=> login command: --export is ephemeral

charmcraft/templates/init/tests/test_charm.py.j2, requirements-dev.txt, setup.py
The introduction of more realistic container networking in the test suite broke the init template tests. I know we're looking at updating the template anyway, but this should be considered a bug fix in the mean time.
In order for the `charmcraft` tests to pass, the `ops` version in `requirements-dev.txt` also needed bumping.
Perhaps we could introduce a CI test that runs charmcraft init; pip install -r requirements-dev.txt; ./run_tests to ensure this doesn't get broken again?
=> Fix the tests in the init template

charmcraft/providers/_logs.py, tests/providers/test_logs.py
Also fixed a small bug of not deleting the file on failure.
=> Save temp retrieved file in current directory so it's fine for the case of running inside a strict snap. (CRAFT-1069)

charmcraft/reactive_plugin.py, tests/test_reactive_plugin.py
=> Do not modify the charm's project when packing using the reactive plugin (CRAFT-928).

charmcraft/commands/store/__init__.py, completion.bash, tests/commands/test_store_commands.py
Added comments in the PR for those formats that do NOT follow the spec (I'd later fix the document if we all agree that the new format is better).
---
CRAFT-1101
=> Second batch of commands with added --format=json for programmatic output.

charmcraft/config.py, charmcraft/deprecations.py, tests/commands/test_build.py, tests/conftest.py, tests/test_config.py, tests/test_main.py
Of course this not only led to the change in the code, but to a lot of
config not-bases-related tests where I had to add 'bases'. Note that in
a lot of cases I just changed the 'type' to 'bundle' (where being a
charm was not relevant to the test) to minimize the amount of changes.
Fixes #655.
=> Enforced DN03: the 'bases' is now mandatory for charms in the config (CRAFT-785).

charmcraft/commands/build.py, charmcraft/commands/pack.py, charmcraft/deprecations.py, charmcraft/main.py, completion.bash, tests/commands/test_build.py, tests/commands/test_pack.py
The Validator, also used from `pack`, no longer makes sense:
- bases_index: moved this control to the Pack command.
- `from`: this was filled with the result of --project-dir, which already verified that the directory existed
- `destructive_mode`, `debug`, `shell`, `shell_after` and `force`: just converted an already bool to bool
Left for next PR: move the `Builder` class and helper function/constants to the `pack.py` file (which would be a huge diff, specially because of tests, but without semantic changes).
=> Removed the long time deprecated 'build' command (CRAFT-1109).

README.md
The README refers to the process of building a charm by invoking
`charmcraft build`, but that command is (no longer) available.
Looking at the code, a transition is being made from build.py to pack.py
and the command to build the charm is also `pack`.
I've renamed it to reflect this for the current version (2.0.0).
=> docs(README): Replace obsoleted build command

tests/commands/test_build.py, tests/test_parts.py
I started running the test suite in a different way and found that some tests failed because "couldn't run `apt`". That was totally a leak, and tests running apt scare me.
So I fixed/simplified them. In detail:
- `test_parts.TestPartsLifecycle.test_run_actions_progress`: used a "null plugin"; using the charm one was irrelevant for what is being tested (that progress was informed for the different actions).
- `test_build.test_build_basic_complete_structure`: this was more like an "integration test" from the very first days, it doesn't make much sense since the real charm building is responsibility of the `charm_builder.py` script, and it was patched more and more in the last months, and this was the final nail in the coffin. Its conceptual flaw is that it uses the external machinery and …
=> Fixed/simplified some tests to isolate them of underlying apt.

charmcraft/commands/build.py, charmcraft/providers/providers.py, tests/providers/test_providers.py
- `create_build_plan` is now in a common location so other commands can access it
- `create_build_plan` returns a list of named tuples
- Added a comprehensive set of unit tests.  Previously, this function was only being tested indirectly.
As the new `craft-providers` interface is built out, the directory `charmcraft/providers/` will be split into 2 places:
1. `charmcraft/providers.py` for charmcraft-specific code
2. The `craft-providers` library
The code in the `charmcraft/providers/` directory will be split piece-by-piece, in a series of small PRs.
Once all the code is finally split, the file `charmcraft/providers/providers.py` will be moved to `charmcraft/providers.py`. Then, the directory will be removed. Finally, all references to the intermediate …
=> create_build_plan: refactor

requirements-dev.txt, requirements.txt
Bump `craft-providers` to `1.4.1` to fix a bug in the truncation of long hostnames when creating an instance.
=> requirements: update craft-providers to 1.4.1

.gitmodules, spread.yaml, tests/spread/commands/version/task.yaml
This is "just enough" spread to run locally considering one has google credentials to run with.
---
CRAFT-1367
```
$ spread google:
2022-09-13 19:22:51 Project content is packed for delivery (100.22MB).
2022-09-13 19:22:51 If killed, discard servers with: spread -reuse-pid=662378 -discard
2022-09-13 19:22:51 Allocating google:fedora-35-64...
2022-09-13 19:22:51 Allocating google:ubuntu-22.04-64...
2022-09-13 19:22:51 Allocating google:ubuntu-20.04-64...
2022-09-13 19:22:51 Allocating google:ubuntu-18.04-64...
2022-09-13 19:23:00 Waiting for google:fedora-35-64 (sep132222-895658) to boot at 34.139.76.162...
2022-09-13 19:23:01 Waiting for google:ubuntu-22.04-64 (sep132222-895807) to boot at 34.148.61.82...
2022-09-13 19:23:02 …
```
=> tests: bootstrap spread

charmcraft/reactive_plugin.py, tests/test_reactive_plugin.py
This patch adds the ability to pass arguments to the `charm build` command when using the reactive plugin.
Example charmcraft.yaml:
```yaml
type: charm
parts:
charm:
plugin: reactive
reactive-charm-build-arguments:
- --binary-wheels-from-source
build-packages:
- tox
- git
- python3-dev
- libffi-dev
source: src/
build-snaps:
- charm/latest/edge
build-environment:
- CHARM_INTERFACES_DIR: $CRAFT_PROJECT_DIR/interfaces/
- CHARM_LAYERS_DIR: $CRAFT_PROJECT_DIR/layers/
```
Fixes: #809
Signed-off-by: Frode Nordahl <frode.nordahl@canonical.com>
=> reactive_plugin: Support arguments to charm build command

charmcraft/templates/init-simple/pyproject.toml.j2
Without this, isort will make a single import line with 88<n_chars<99 into a multi-line import, and black will convert it back to a single line. They will never pass at the same time.
Improvement brought from https://github.com/canonical/template-operator/pull/36 .
=> Set isort line_length in the init templates to same as other tools.

charmcraft/commands/store/__init__.py, charmcraft/commands/store/registry.py, tests/commands/test_store_commands.py, tests/commands/test_store_registry.py
Also be very explicit on which one is used when. It results on being quicker if the id is used (no check on remote registry) and better messages to the user. Which were improved also: not all needed to be permanent, and actually ended in error if the image to upload is not found and nothing can be done.
Fixes #853.
=> Support both image id and digest when uploading oci-image resources (CRAFT-1324).

charmcraft/providers/_provider.py, charmcraft/providers/providers.py, tests/commands/test_build.py, tests/commands/test_clean.py, tests/providers/test_lxd.py, tests/providers/test_multipass.py, tests/providers/test_provider.py, tests/providers/test_providers.py
`is_base_available()` contains charmcraft-specific logic, so it is separated from the craft-providers interface
=> providers: move `is_base_available()` to providers.py

charmcraft/commands/store/__init__.py, charmcraft/commands/store/store.py, completion.bash, tests/commands/test_store_api.py, tests/commands/test_store_commands.py
=> (charmhub) Support including collaborations when listing registered names (CRAFT-878).

charmcraft/commands/store/__init__.py, tests/commands/test_store_commands.py
=> (charmhub) Don't show repeated branches in Status command results (CRAFT-1270).

charmcraft/commands/store/__init__.py, charmcraft/commands/store/registry.py, tests/commands/test_store_registry.py
I have consistently encountered an error when trying to upload an OCI image resource by digest,
```
2022-10-19 18:48:50.975 Checking if manifest is already uploaded
2022-10-19 18:48:54.748 Remote image not found, getting its info from local registry.
2022-10-19 18:48:54.752 charmcraft internal error: TypeError("'NoneType' object is not iterable")
2022-10-19 18:48:54.757 Traceback (most recent call last):
2022-10-19 18:48:54.757   File "/snap/charmcraft/1083/lib/charmcraft/main.py", line 180, in main
2022-10-19 18:48:54.757     retcode = dispatcher.run()
2022-10-19 18:48:54.757   File "/snap/charmcraft/1083/lib/craft_cli/dispatcher.py", line 448, in run
2022-10-19 18:48:54.757     return self._loaded_command.run(self._parsed_command_args)
2022-10-19 18:48:54.757   File …
```
=> Fix for getting image info from digest

charmcraft/templates/init-kubernetes/tests/integration/test_charm.py.j2, charmcraft/templates/init-machine/tests/integration/test_charm.py.j2, charmcraft/templates/init-simple/tests/integration/test_charm.py.j2
The integration tests already do `charm = await
ops_test.build_charm(".")` earlier, so it doesn't make sense to await again on the result of that.
Fixes #910.
=> templates: remove duplicate "await"

spread.yaml, tests/spread/store/bundle-upload-and-release/task.yaml, tests/spread/store/charm-upload-and-release/task.yaml
Avoided to get "last" revision because the uploaded one may not be the latest one (because other concurrently running test may have uploaded other one).
=> Made pack & upload tests more robust.

charmcraft/templates/init-kubernetes/tests/unit/test_charm.py.j2, charmcraft/templates/init-machine/tests/unit/test_charm.py.j2, charmcraft/templates/init-simple/pyproject.toml.j2, charmcraft/templates/init-simple/src/charm.py.j2, charmcraft/templates/init-simple/tests/unit/test_charm.py.j2, charmcraft/templates/init-simple/tox.ini.j2
We have previously standardised on using `flake8` with a number of plugins, and `pyproject-flake8` to enable us to configure all of our linting tools in one place (`pyproject.toml`)
Over the past months, there have been two major releases of `flake8`, and both have caused various issues with the various plugins and their dependencies, leading to instability in CI pipelines.
I've been following [ruff](https://github.com/charliermarsh/ruff) for a while. It's a Python linter, written in Rust, that combines a lot of the rules we were using from these other plugins. It's actively maintained, and all under one project, reducing the complexity of the dependency tree a little. It's got adoption from some pretty large projects like FastAPI and pydantic.
Proposing here for discussion.
=> feat: replace flake8 + plugins and isort with ruff

.github/renovate.json5
Based on [this comment](https://github.com/canonical/charmcraft/pull/948#pullrequestreview-1213392441)
If we later need to ignore specific requirements files we can add an `ignorePaths` array to the base config.
=> Update Renovate config to match all requirements-*.txt files.

charmcraft/cmdbase.py, tests/test_main.py
This commit add the option to format the output data in yaml format and also updates the text for charmcraft status --help for --format option.
Fixes #794
=> Update the charmcraft status --format

charmcraft/parts.py, tests/test_parts.py
Currently, if you stare at the screen when the charm builder is run, at some point the plugin executes the charm builder and the last thing that is seen for a long time is
```
2023-01-17 13:36:46.136 :: + env -i LANG=C.UTF-8 LC_ALL=C.UTF-8 PATH=/snap/charmcraft/1171/libexec/charmcraft:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin SNAP=/snap/charmcraft/1171 SNAP_ARCH=amd64 SNAP_NAME=charmcraft SNAP_VERSION=2.2.0 /snap/charmcraft/1171/bin/python3 -I /snap/charmcraft/1171/lib/charmcraft/charm_builder.py --builddir /root/parts/charm/build --installdir /root/parts/charm/install --entrypoint /root/parts/charm/build/src/charm.py -r requirements.txt
```
Running this subprocess in unbuffered mode it will help to retrieve sooner its messages.
=> Run the charm builder with python in unbuffered mode.

charmcraft/commands/store/__init__.py, charmcraft/commands/store/charmlibs.py, charmcraft/errors.py, snap/local/sitecustomize.py, tests/commands/test_store_charmlibs.py, tests/commands/test_store_commands.py, tests/factory.py
Fixes CRAFT-1557
(Side note: I've got an upcoming PR that implements many of the test changes I made in #990 and takes into account the feedback. It'll be based on this one though.)
=> refactor: Move charm library helper functions to their own modules (CRAFT-1557)

charmcraft/commands/store/charmlibs.py, tests/commands/test_store_charmlibs.py
This is a preparation PR before changing the charmlib parsing to use AST. It does not change any code, just move it around, including tests (some of which are collapsed using parametrize).
=> refactor: isolate the charm lib internals extractor

charmcraft/charm_builder.py, charmcraft/commands/build.py, charmcraft/commands/store/__init__.py, charmcraft/commands/store/charmlibs.py, tests/commands/test_build.py, tests/commands/test_store_charmlibs.py, tests/test_charm_builder.py
There are two situations where these dependencies need to be used:
- in the Builder when it decides if the `venv` directory needs to be primed
- in charm_builder when dependencies are actually handled (hashed, installed, etc.)
I created a helper to collect all the dependencies, used from those two places. Located it in the charmlibs module for convenience (initially I thought putting it in `charmcraft/utils` but hit a circular import).
Alternatively, these dependencies could have been collected where other dependencies are defined or dynamically included: in the CharmPluginProperties class. This will make "pydeps" management much more similar to standard python packages or requirements files, but there are several drawbacks of this path:
- a new `charm_libs_deps` or similar key would have …
=> pack: include the charm libraries dependencies (CRAFT-1559)

requirements-dev.txt, requirements.txt
Craft-parts 1.18.1 fixes ignored file patterns when processing local sources.
=> requirements: update craft-parts to 1.18.1

charmcraft/commands/store/__init__.py, tests/commands/test_store_commands.py
The `TEMPLATE-TODO` was a mark used in the `init` command for places where the user should do changes, so it was validated at Upload time (way before we had linters) that everything was properly replaced. But this mark does not exist anymore after `init` was refactored and multiple templates appeared.
=> Remove a verification left over after init command refactor.

.github/workflows/tests.yaml
The Ubuntu-18.04 environment is deprecated and will be removed on April 1st, 2023. For more details, see
https://github.com/actions/runner-images/issues/6002
=> ci: remove deprecated ubuntu 18.04 GitHub CI

charmcraft/commands/store/store.py, tests/commands/test_store_api.py, tests/commands/test_store_commands.py
Avoid wasting time uploading when credentials expire.
=> store: check the credentials validity before upload

requirements-dev.txt, requirements.txt, setup.py, snap/snapcraft.yaml
Since older versions of cryptography now have known security issues, it's more necessary to update. This not only makes that change but also updates the snapcraft.yaml to include the appropriate rust dependencies.
Should fix #991
=> deps: update cryptography to v39.0

charmcraft/parts.py, tests/test_parts.py
The Python 3.8 in CentOS 7 from SCL repo not included in PATH.
=> parts: CentOS 7 python 3.8 path workaround

requirements-dev.txt, setup.py
Spread tests were failing due to this. We're going to have to keep this pre-2.0 until we can guarantee at least Python 3.8 in our spread tests, which will likely only happen when we drop support for 18.04.
=> deps: remove ops dependency

.github/workflows/spread.yaml, spread.yaml, tests/spread/charms/k8s-operator/task.yaml
Separate the logic into two in the Github Actions Workflow to always run spread for the general tests, while limiting store tests to having CHARMCRAFT_AUTH in GHA Secrets.
The required environment has been moved to the store suite in spread. Also making it run less test repetition by limiting them to Ubuntu 22.04 and avoiding it being run in the main testing phase for spread by marking them as manual.
=> ci: only require CHARMCRAFT_AUTH for store spread

.github/workflows/spread.yaml, charmcraft/commands/store/__init__.py, spread.yaml, tests/spread/store/bundle-upload-and-release/task.yaml, tests/spread/store/charm-upload-and-release/task.yaml, tests/spread/store/libraries/task.yaml, tests/spread/store/resources/task.yaml
Depends on #1075. Once that's merged this will be a whole lot cleaner
The actual changes for this PR: https://github.com/canonical/charmcraft/pull/1081/files/82d83e4a1292c5619e66fe4a5045cd04cc828732..HEAD
=> store: ensure promote-bundle succeeds if there are no applications

charmcraft/commands/store/charmlibs.py, tests/commands/test_store_charmlibs.py
Without filtering for ast.Names when looking for ast.Assign, we also falled into looking for assignments of the form
`module_name.method_call().attribute = assignment`
=> charmlibs: skip non top-level name assignments

charmcraft/commands/build.py, charmcraft/parts.py, charmcraft/providers.py, requirements-dev.txt, requirements.txt, tests/commands/test_build.py, tests/conftest.py, tests/spread/smoketests/basic-centos-7/task.yaml, tests/test_parts.py, tests/test_providers.py
needs Ubuntu 18.04 for cgroup v1
needs craft-providers unreleased version.
CRAFT-1697
=> bases: support creating charms use CentOS 7 as base

.github/renovate.json5, .github/workflows/tests.yaml, snap/snapcraft.yaml
This is a quick and dirty workaround to make cryptography build properly.
I'll follow up with a more robust fix, but this should at least get the snap building on all architectures.
Remote build: https://launchpad.net/~lengau/+snap/snapcraft-charmcraft-1bebeb44e32b4aa985026c6f977fd0b8
=> snap: ensure cryptography builds correctly on all architectures

charmcraft/commands/store/__init__.py, charmcraft/commands/store/store.py, tests/spread/store/bundle-upload-and-release/task.yaml
Make channel parameters options instead of positional arguments and display what was done at the end (which also gets rid of an upload artifact left over from the last progress message).
=> commands: cosmetic fixes to promote-bundle

charmcraft/commands/build.py, charmcraft/commands/pack.py, charmcraft/commands/store/__init__.py, charmcraft/config.py, charmcraft/metafiles/__init__.py, charmcraft/metafiles/actions.py, charmcraft/models/config.py, tests/spread/smoketests/metafiles/actions/task.yaml, tests/test_actions.py, tests/test_config.py
This allow we define actions in the same file rather than separated actions.yaml.
This also included some refactor to avoid circular imports.
CRAFT-1746
=> config: support use actions in charmcraft.yaml

charmcraft/commands/build.py, charmcraft/const.py, requirements-dev.txt, requirements.txt, tests/spread/smoketests/basic-non-lts/task.yaml, tests/test_providers.py
Allow user create charms with non-LTS Ubuntu versions.
User will get warning when building on those versions.
CRAFT-1759
=> bases: allow builds with ubuntu non-lts

charmcraft/bases.py, charmcraft/commands/build.py, charmcraft/config.py, charmcraft/linters.py, charmcraft/metafiles/manifest.py, charmcraft/models/basic.py, charmcraft/models/charmcraft.py, charmcraft/providers.py, tests/commands/test_build.py, tests/commands/test_clean.py, tests/commands/test_init.py, tests/commands/test_pack.py, tests/commands/test_store_commands.py, tests/conftest.py, tests/test_bases.py, tests/test_config.py, tests/test_manifest.py, tests/test_providers.py
Common models moved to basic.py
Charmcraft Config model moved to charmcraft.py and renamed to CharmcraftConfig to avoid confuse with juju's config.
=> pydantic: split base and charmcraft config models

.github/workflows/spread.yaml, tests/spread/charms/bundle/task.yaml, tests/spread/charms/k8s-operator/task.yaml
Related to #1193, this should make our CI succeed. We will need to re-enable these tests once the issues with those charms are resolved.
=> ci: temporarily disable externally broken spread tests

requirements-bionic.txt, requirements-focal.txt, requirements-jammy.txt
Bionic has entered ESM, we also no longer support the Python included in 18.04.
=> packaging: update apt requirements, remove bionic

charmcraft/metafiles/actions.py, charmcraft/metafiles/config.py, charmcraft/metafiles/metadata.py, charmcraft/models/actions.py, charmcraft/models/charmcraft.py, charmcraft/models/config.py, charmcraft/models/metadata.py, tests/spread/smoketests/metafiles-bad-yaml-unenforced/task.yaml, tests/spread/smoketests/metafiles-multiple-yaml/task.yaml, tests/spread/smoketests/metafiles-unified-charmcraft-yaml/task.yaml, tests/test_config.py, tests/test_metadata.py, tests/test_metafiles.py, tests/test_models.py
Only warning when found invalid file for backward compatible.
Fixes #1208
=> models: do not enforce pydantic models on legacy files

charmcraft/commands/pack.py, charmcraft/package.py, tests/commands/test_pack.py, tests/test_package.py
=> refactor: move builder out of the commands directory.

charmcraft/templates/init-machine/charmcraft.yaml.j2
This change should make the `charm-upload-and-release` store task pass.
Progress on #1193
=> templates: remove k8s info from machine charm template

requirements-dev.txt, requirements.txt, snap/hooks/configure, tests/spread/smoketests/lxd/task.yaml
- Update base compatibility tag from `base-v1` to `base-v2`
- Use `snap refresh --hold` inside instances
- Re-level log messages
- Add more info-level log messages
- Update links from linuxcontainers.org to ubuntu.com
- Set timezone of LXD instances to match host's timezone
- Add name and install recommendations to Providers
Resolves #1202 
(CRAFT-1953)
=> requirements: bump craft-providers

spread.yaml
This allows multiple simultaneous workers with multipass using the same naming scheme the built-in lxd backend uses.
=> tests: improve multipass spread backend

charmcraft/commands/store/__init__.py, tests/commands/test_store_commands.py
Resource test is fixed in #1223
=> store: allow publish-lib to work without a metadata.yaml

.github/workflows/tests.yaml
This will also need adjustments to our required checks.
* Remove Python 3.9 tests (no longer widely used in any of our use cases)
* Use only built-in Python versions on Ubuntu releases (but ready to add 3.12 for 24.04)
* Add 3.11 (current latest) on Windows/mac
=> ci: reduce the python/OS matrix size

.github/workflows/tests.yaml, charmcraft/cmdbase.py, charmcraft/commands/store/__init__.py, charmcraft/models/charmcraft.py, pyproject.toml, snap/hooks/configure, tests/commands/test_store_charmlibs.py, tests/commands/test_store_registry.py, tests/test_config.py, tests/test_infra.py, tests/test_main.py, tests/test_metadata.py, tests/test_models.py, tests/test_package.py
This is broken into two commits, first fixing spelling and then enabling codespell.
=> ci: enable codespell

charmcraft/commands/analyze.py, charmcraft/linters.py, charmcraft/metafiles/manifest.py, charmcraft/models/basic.py, charmcraft/package.py, tests/commands/test_analyze.py, tests/test_config.py, tests/test_linters.py, tests/test_manifest.py, tests/test_package.py
Before this was essentially a singleton namedtuple instance, which can be harder for tools to evaluate.
=> refactor(linters): make CheckType an enum

tests/test_package.py
I wouldn't normally care, but a codespell update is causing us to fail CI due to this.
=> style: fix spelling of "processor"

requirements-focal.txt, requirements-jammy.txt, snap/snapcraft.yaml
This change caches the python-apt wheel, speeding up repeated builds of the snap in the same provider.
=> perf(snap): speed up repeat snap builds

tests/commands/test_init.py, tests/test_infra.py
Also moves the functions only used when testing the init command to the appropriate file.
We're removing these because they're duplicated by our use of ruff.
=> test(style): remove pydocstyle tests on charmcraft code

charmcraft/commands/analyze.py, charmcraft/linters.py, charmcraft/models/lint.py, charmcraft/package.py, tests/commands/test_analyze.py, tests/test_linters.py, tests/test_package.py
* Moves data structures into models
* Base classes for checkers
* Constant classes for results
* LintResult is no longer an enum
=> refactor(linters): stricter typing for linters

charmcraft/package.py
Support Ubuntu 23.10. Also fixed a message display issue.
=> fix(cli): make non-LTS build warning permanent

requirements-dev.txt, requirements.txt, snap/hooks/configure
- Update base compatibility tag from ``base-v2`` to ``base-v3``
This fixes an issue where LXD instances created with
``craft-providers==1.16.0`` may fail to start with
``craft-providers>=1.17.0``.
- Require a disk device in the default LXD profile
=> build(deps): bump craft-providers to 1.19.2

snap/local/sitecustomize.py, snap/snapcraft.yaml
fixes #1369 
Multi-platform build: https://launchpad.net/~lengau/+snap/snapcraft-charmcraft-084dfcb7321972fd248f5d75baf555ca
=> fix: make snap build on all architectures.

tests/spread/smoketests/basic-centos-7/task.yaml, tests/spread/smoketests/basic/task.yaml, tests/spread/smoketests/different-dependencies/task.yaml, tests/spread/smoketests/full-lifecycle/task.yaml
We've got a few places where we use grep directly in a way that doesn't guarantee test failure when it should.
=> test: use MATCH in spread tests

charmcraft/linters.py, charmcraft/templates/init-kubernetes/charmcraft.yaml.j2, charmcraft/templates/init-kubernetes/pyproject.toml.j2, charmcraft/templates/init-machine/charmcraft.yaml.j2, charmcraft/templates/init-machine/pyproject.toml.j2, charmcraft/templates/init-simple/charmcraft.yaml.j2, charmcraft/templates/init-simple/pyproject.toml.j2, tests/test_linters.py
Patch the metadata linter to fail if the 'series' key is present. For a long time charmcraft has generated a manifest.yaml on pack which has been used instead series in metadata.
Juju ignores 'series' in metadata for any packed charm (i.e. a charm with a manifest.yaml)
There is an effort to remove the notion of a series from Juju entirely, substituting it for bases. As such, Juju is roadmapped to deprecate support for charms without manifest.yaml files in 3.4, removing support entirely in 4.0 (i.e. showing an error).
Showing a linter error in `charmcraft analyze` will be a convenient way to begin communicating this
As a flyby fix, remove whitespace from the end of line in the templates
```
$ juju download kafka
Fetching charm "kafka" revision 123 using "stable" channel and base …
```
=> feat: deprecate 'series' in metadata.yaml & patch linter

.github/workflows/tests.yaml, CONTRIBUTING.md, requirements-dev.txt, setup.py, tox.ini
Uses the version of ruff from snap in CI and tox.
Testing this in charmcraft as a canary before changing all of our repos over.
=> build: use ruff snap

setup.py
See: https://github.com/python/typeshed/blob/011f24794d334ecbd6bda104a8e57399bd6bcad8/stubs/requests/METADATA.toml
=> chore(deps): freeze types-requests for urllib3 compatibility.

charmcraft/charm_builder.py, tests/test_charm_builder.py
fixes #1374
Pip 22 doesn't use the prebuilt wheel cache when using `--no-binary=[list of packages]`, but does when using `--no-binary=:all:`. As such, using strict dependencies won't use the cache with pip 22
Has potential regressions, so I'm going to run a large spread on this: https://github.com/canonical/charmcraft/actions/runs/7184537100
EDIT: Large spread failures are unrelated and are fixed in https://github.com/canonical/charmcraft/pull/1438. This should be cherry-picked to the 2.5 branch.
=> fix(charm_builder): bump minimum pip version to 23

.github/workflows/spread-large.yaml, .github/workflows/spread.yaml, .github/workflows/tests.yaml
This update has a breaking change that each workflow needs separate jobs.
See: https://github.com/actions/upload-artifact#breaking-changes
=> ci(deps): update upload-artifact action

snap/local/sitecustomize.py, snap/snapcraft.yaml
This is a cherry-pick of commit f5558b8f39faf96332be63b to get this feature-branch working again and give us some breathing room until we can fully merge `origin/main` (which needs to migrate the extension support to the new craft-application-based code).
Original commit message:
----------
Multi-platform build:
https://launchpad.net/~lengau/+snap/snapcraft-charmcraft-084dfcb7321972fd248f5d75baf555ca
=> fix: make snap build on all architectures. (#1377)

tests/integration/commands/test_init.py
This is a temporary workraound for #1508, to allow CI to pass while we're figuring it out.
(snap build failures are due to launchpad's current outage)
=> test: ignore failing init test on macos 11

README.md
Currently PRs to main are included in those badges, meaning that if tests fail on those PRs it shows failing.
=> docs: make badges only use what's actually on main

tests/commands/test_list_extensions.py
Classes that aren't used for test organisation shouldn't start with `Test`. Pytest 8 breaks if they do.
=> test: rename fake extensions

tests/integration/commands/test_init.py
This PR was created to find the source of #1508, but it will be useful for other failures too.
macos 11 failure is what this PR is meant to debug, so it won't hurt to merge while that's failing.
=> test: make init tox test more informative

charmcraft/services/provider.py
When running pack the experimental extensions environment variable is not passed anymore to the provider environment leading to pack errors if using an extensions that requires it
=> fix: Pass missing experimental flag when running pack

charmcraft/application/commands/lifecycle.py, charmcraft/application/main.py, charmcraft/extensions/__init__.py, charmcraft/extensions/bundle.py, charmcraft/parts/bundle.py, tests/integration/commands/test_extensions.py, tests/integration/commands/test_pack.py, tests/unit/commands/test_lifecycle.py, tests/unit/extensions/test_bundle.py, tests/unit/parts/test_bundle.py
This creates a basic extension that automatically fills in the parts for a bundle and default-enables it for bundles.
Future additions could include reading `bundle.yaml` into the bundle project.
Motivation for this was fixing bundle builds in the ca-2 feature branch
=> feat(extensions): add bundle extension

tests/spread/smoketests/basic/charmcraft-20.04.yaml, tests/spread/smoketests/basic/charmcraft-22.04.yaml, tests/spread/smoketests/basic/charmcraft-23.10.yaml, tests/spread/smoketests/basic/charmcraft-alma9.yaml, tests/spread/smoketests/basic/task.yaml, tests/spread/smoketests/full-lifecycle/charmcraft-kubernetes.yaml, tests/spread/smoketests/full-lifecycle/charmcraft-machine.yaml, tests/spread/smoketests/full-lifecycle/charmcraft-simple.yaml, tests/spread/smoketests/full-lifecycle/task.yaml
We're about to have a lot more variants of `charmcraft.yaml` to spread test. This makes it far more straightforward than trying to manipulate charmcraft.yaml during the prepare step.
=> refactor(tests/spread): test with explicit charmcraft.yaml files

pyproject.toml, requirements-dev.txt, requirements.txt
Remote build failure is fine: https://github.com/canonical/charmcraft/issues/1566
=> chore: bump craft-providers to 1.23

charmcraft/env.py, requirements-dev.txt, requirements.txt
`distutils` is removed in Python 3.12, use `craft-applicaion.util` replace it.
Fixes: #1527
=> fix: remove distutils and use craft-application.util

charmcraft/templates/init-kubernetes/tests/unit/test_charm.py.j2, charmcraft/templates/init-machine/tests/unit/test_charm.py.j2, charmcraft/templates/init-simple/src/charm.py.j2, charmcraft/templates/init-simple/tests/unit/test_charm.py.j2
Related to https://github.com/canonical/operator/issues/1110.
I kept the changes as minimal as possible.
=> tests (templates): Use pytest fixtures and asserts instead of unittest

charmcraft/linters.py, charmcraft/parts/charm.py, tests/test_linters.py
Add extra files should use the dump plugin, not use the prime keywords.
This will errors any extra files added without using the proper ways.
=> feat(linter): add additional-files linter

charmcraft/application/main.py, charmcraft/models/project.py, charmcraft/preprocess.py, tests/integration/sample-charms/actions-included/charmcraft.yaml, tests/integration/sample-charms/actions-included/expected.yaml, tests/integration/sample-charms/actions-separate/actions.yaml, tests/integration/sample-charms/actions-separate/charmcraft.yaml, tests/integration/sample-charms/actions-separate/expected.yaml, tests/integration/sample-charms/basic-bases/charmcraft.yaml, tests/integration/sample-charms/basic-bases/expected.yaml, tests/integration/sample-charms/basic-platforms/charmcraft.yaml, tests/integration/sample-charms/basic-platforms/expected.yaml, tests/integration/sample-charms/config-included/charmcraft.yaml, tests/integration/sample-charms/config-included/expected.yaml, tests/integration/sample-charms/config-separate/charmcraft.yaml, tests/integration/sample-charms/config-separate/config.yaml, tests/integration/sample-charms/config-separate/expected.yaml, tests/integration/test_application.py, tests/unit/test_preprocess.py
=> feat: add config and actions processing to _extra_yaml_transform

charmcraft/extensions/gunicorn.py, charmcraft/templates/init-flask-framework/requirements.txt.j2, charmcraft/templates/init-flask-framework/src/charm.py.j2, tests/extensions/test_gunicorn.py
As charmcraft will not automatically add the default `charm` part if extensions are in use, the `flask-framework` extension should include the charm part. Furthermore, as the `flask-framework` extension is designed exclusively for `ops` based charms, it should incorporate a check to ensure that there is no customized charm part in `charmcraft.yaml` that could potentially conflict with the extension.
Some miscellaneous changes include the use of new library packages in the template `requirements.txt`.
Fix: https://github.com/canonical/charmcraft/issues/1616
=> fix: add default charm part in flask-framework

charmcraft/application/main.py, charmcraft/preprocess.py, tests/unit/models/test_project.py, tests/unit/models/valid_charms_yaml/basic-bases.yaml, tests/unit/test_preprocess.py
This makes a few related changes:
1. Extensions are applied on the rawest charmcraft.yaml data we have
2. Charms with a "bases" key (not just bundles) get a default part.
3. Always expect a dictionary for parts.
=> fix: reorganise charmcraft.yaml preprocessing

charmcraft/extensions/gunicorn.py, charmcraft/templates/init-flask-framework/requirements.txt.j2, tests/extensions/test_gunicorn.py, tests/spread/commands/init-flask-framework/task.yaml
We have now tested the extension with the web team and they are happy with. This means we're ready to move the `flask-framework` extension to be stable.
=> remove experimental flag for flask-framework extension

requirements-dev.txt, requirements.txt
This bumps only craft-providers and craft-store to match the minor versions used by snapcraft 7.x
=> build(deps): bump internal libraries

charmcraft/application/commands/store.py, charmcraft/commands/store.py, charmcraft/errors.py, charmcraft/store/client.py, charmcraft/utils/charmlibs.py, tests/commands/test_pack.py, tests/commands/test_store_commands.py, tests/commands/test_store_registry.py, tests/test_jujuignore.py, tests/unit/utils/test_charmlibs.py
This was created entirely by running `tox -f format` to run all the autoformatters.
=> style: autoformat to fix for ruff 0.4

charmcraft/templates/init-simple/src/charm.py.j2, tests/integration/commands/test_init.py, tox.ini
Includes both a fix for the environment variable and a workaround for https://github.com/canonical/operator/issues/1212
=> fix: make tox tests succeed

charmcraft/application/commands/store.py, tests/conftest.py, tests/unit/commands/test_store.py
Fixes #1672
Test failures are fixed in https://github.com/canonical/charmcraft/pull/1674
=> fix: fix login crash

charmcraft/application/commands/test.py, charmcraft/templates/init-kubernetes/spread.yaml.j2, charmcraft/templates/init-machine/spread.yaml.j2, charmcraft/templates/init-simple/spread.yaml.j2, pyproject.toml
Let the test command parse its arguments instead of forwarding them
to spread in raw form. This allows us to use consistent double-dashed
long options, and have better help messages.
=> fix(test): parse test command arguments

.github/workflows/tests.yaml, charmcraft/application/commands/store.py, charmcraft/application/main.py, charmcraft/errors.py, charmcraft/services/__init__.py, charmcraft/services/image.py, charmcraft/store/store.py, charmcraft/utils/__init__.py, charmcraft/utils/file.py, charmcraft/utils/skopeo.py, pyproject.toml, requirements-dev.txt, requirements.txt, snap/snapcraft.yaml, tests/integration/utils/test_skopeo.py, tests/spread/store/resources/task.yaml, tests/unit/commands/test_store.py, tests/unit/services/test_image.py, tests/unit/services/test_store.py, tests/unit/utils/test_skopeo.py
Fixes #1684,  partial for #1685
=> feat: upload OCI image resources with skopeo

.github/workflows/tests.yaml, CODE_OF_CONDUCT.md, charmcraft/commands/store/__init__.py, charmcraft/errors.py, charmcraft/templates/init-kubernetes/src/charm.py.j2, charmcraft/templates/init-machine/src/charm.py.j2, charmcraft/templates/init-simple/src/charm.py.j2, charmcraft/utils/__init__.py, charmcraft/utils/skopeo.py, snap/snapcraft.yaml, tests/commands/test_store_commands.py, tests/spread/store/resources/task.yaml, tests/test_infra.py, tests/unit/utils/test_skopeo.py
Allows Charmcraft 2.7+ to use skopeo urls directly when uploading an oci-image resource.
Example:
```
$ charmcraft upload-resource lengau-test-charm example-image --image docker://ghcr.io/canonical/charmed-mysql:8.0.36-22.04_edge
Image not found locally. Passing path directly to skopeo.                                         
Revision 6 created of resource 'example-image' for charm 'lengau-test-charm'.      
$
```
=> feat: backport rock upload to charmcraft 2.x

.github/workflows/publish-pypi.yaml, .gitignore, HOWTO_RELEASE.md, pyproject.toml, tox.ini
Adds two Tox environments that help with publishing the Python package on PyPI.
- `tox -e package` can be used for linting to help detect packaging issues.
- `tox -e package -- upload` allows to publish the package on PyPI.
- `tox -e ensure_version_matches $GIT_TAG` verifies that the package version matches the semantic Git tag on the current commit. This is used by the GHA configuration to prevent a mismatch of tags and the version of the published package.
To make publishing work, you need to add the 2 secrets `PYPI_USERNAME` and `PYPI_PASSWORD` to [Settings ➜ Secrets ➜ Actions](https://github.com/canonical/charmcraft/settings/secrets/actions) with the PyPI access token for the project, as described in the [Python packaging user …
=> Automate publishing Python package on PyPI

.gitignore, .readthedocs.yaml, charmcraft/application/commands/store.py, charmcraft/format.py, charmcraft/instrum.py, charmcraft/jujuignore.py, charmcraft/metafiles/actions.py, charmcraft/models/__init__.py, charmcraft/models/charmcraft.py, charmcraft/models/project.py, charmcraft/providers.py, docs/_static/css/custom.css, docs/conf.py, docs/explanation/index.rst, docs/howto/index.rst, docs/index.rst, docs/reference/commands.rst, docs/reference/index.rst, docs/reference/models/bases-charm.rst, docs/reference/models/index.rst, docs/tutorials/index.rst, pyproject.toml, tools/gen_cli_docs.py, tox.ini
Adds a Sphinx documentation project and some basic documentation. The purpose is to allow automatic generation of certain reference documentation that would otherwise need to be manually generated for juju.is.
This includes using the Starcraft standard `starbase` sphinx docs, A command documentation generator from rockcraft, and additions to some pydantic models to copy documentation out of what's on juju.is.
Fixes #1692
=> feat: add basic sphinx docs

charmcraft/extensions/gunicorn.py, tests/extensions/test_gunicorn.py
This is needed because flask has an indirect dependency on rust-based modules.
Snap store test is unrelated (#1712)
=> fix(flask): include cargo build-dep

charmcraft/utils/package.py, tests/test_charm_builder.py, tests/unit/test_charm_builder.py, tests/unit/utils/test_package.py
This reduces the chances of having pip install binary packages as indirect dependencies.
Partial fix for #1473
=> fix(pip): set `--no-binary=:all:` if possible

charmcraft/utils/file.py, tests/unit/utils/test_file.py
Makes `build_zip` use the Charmcraft 2.x behaviour of following symlinks even for directories:
https://github.com/canonical/charmcraft/blob/2.7.1/charmcraft/package.py#L440
This ensures that not only symlinked files, but also symlinked dirs are included in the resulting charm or bundle.
Fixes #1719
=> fix(zip): include linked directories in created zips

charmcraft/extensions/gunicorn.py, tests/extensions/test_gunicorn.py, tests/spread/commands/init-flask-framework/task.yaml
A new update to a flask dependency requires a more recent version of rustc than is available in the jammy repos.
This works around that by using the same rustup snap as the craft-parts rust plugin
Fixes #1743
Spread test failure is fixed in https://github.com/canonical/charmcraft/pull/1749
=> fix(flask): use rustup snap

charmcraft/charm_builder.py, tests/test_charm_builder.py
Ensure that charmlibs that are already installed using requirements.txt don't get additionally listed on the command line, as this can break pip.
Spread test failures are fixed in #1744 and #1749
=> fix(charm_builder): de-duplicate installed pkgs

tox.ini
Failure example: https://github.com/canonical/charmcraft/actions/runs/10062480068/job/27815089103
=> fix(ci): fix tox ensure_version_matches

charmcraft/models/metadata.py, tests/unit/models/test_metadata.py
Fixes #1758
More context in https://github.com/canonical/charmcraft/issues/1568
=> fix(metadata): allow long summaries in output

charmcraft/charm_builder.py, tests/integration/test_charm_builder.py, tests/spread/dependencies/strict-dependencies-errors/missing-packages/charmcraft.yaml, tests/spread/dependencies/strict-dependencies-errors/missing-packages/pyproject.toml, tests/spread/dependencies/strict-dependencies-errors/missing-packages/requirements.txt, tests/spread/dependencies/strict-dependencies-errors/missing-packages/src/charm.py, tests/spread/dependencies/strict-dependencies-errors/task.yaml, tests/spread/dependencies/strict-dependencies/charm/charmcraft.yaml, tests/spread/dependencies/strict-dependencies/charm/requirements.txt, tests/unit/test_charm_builder.py
This runs `pip check` to ensure that all the packages in the charm virtualenv have all of their required dependencies, failing the build if they do not.
Fixes #1781
=> fix(strict-deps): fail if venv is inconsistent

charmcraft/charm_builder.py, tests/integration/test_charm_builder.py, tests/spread/dependencies/strict-dependencies-errors/missing-packages/charmcraft.yaml, tests/spread/dependencies/strict-dependencies-errors/missing-packages/pyproject.toml, tests/spread/dependencies/strict-dependencies-errors/missing-packages/requirements.txt, tests/spread/dependencies/strict-dependencies-errors/missing-packages/src/charm.py, tests/spread/dependencies/strict-dependencies-errors/task.yaml, tests/spread/dependencies/strict-dependencies/charm/charmcraft.yaml, tests/spread/dependencies/strict-dependencies/charm/requirements.txt, tests/unit/test_charm_builder.py
This runs `pip check` to ensure that all the packages in the charm virtualenv have all of their required dependencies, failing the build if they do not.
Fixes #1781
=> fix(strict-deps): cherry-pick #1784 into 3.1 hotfix branch

charmcraft/application/main.py
Excludes both previous charm files and charmcraft.yaml from the output charm file.
Fixes #1791
=> fix(application): exclude files from charm

charmcraft/services/package.py, charmcraft/utils/yaml.py, tests/conftest.py, tests/integration/services/sample_projects/complex-legacy/prime/manifest.yaml, tests/integration/services/sample_projects/complex-self-contained/prime/manifest.yaml, tests/unit/models/test_project.py, tests/unit/services/test_package.py
For a `bases` charm, this was previously writing out all run bases rather than the specific bases for this build.
=> fix(package): Limit the bases in manifest.yaml

tests/spread/smoketests/lxd/task.yaml
The lxd smoke test was timing out. This speeds it up at the cost of having it build a broken charm.
=> fix(tests): speed up lxd smoke test

.github/workflows/tics.yaml, pyproject.toml, requirements-dev.txt
=> ci: add support for tiobe

.github/workflows/tests.yaml, charmcraft/parts/__init__.py, charmcraft/preprocess.py, tests/integration/sample-charms/actions-included/expected.yaml, tests/integration/sample-charms/actions-separate/expected.yaml, tests/integration/sample-charms/basic-bases/expected.yaml, tests/integration/sample-charms/basic-platforms/expected.yaml, tests/integration/sample-charms/config-included/expected.yaml, tests/integration/sample-charms/config-separate/expected.yaml, tests/test_parts.py, tests/unit/models/test_project.py, tests/unit/models/valid_charms_yaml/basic-bases.yaml, tests/unit/test_parts.py, tests/unit/test_preprocess.py
The pydantic 2 change caused some weirdness in adding default parts, so this fixes it. After this, pydantic 2 should be ready to merge to main.
=> fix(yaml): correctly add default parts

tests/spread/smoketests/basic/task.yaml
Mantic is EOL so we need to remove this test for CI to pass for bugfix releases to the 2.7 branch
=> tests(2.7): remove mantic spread test

charmcraft/commands/store/__init__.py
Fixes this error:
```
+ charmcraft upload-resource gh-ci-charmcraft-charm example-image --image=docker://hello-world@sha256:18a657d0cc1c7d0678a3fbea8b7eb4918bba25968d3e1b0adebfa71caddbc346
Uploading resource from image charm/co44x4qvu12a2ff5a1v04haywbiyhc0uv6erc/example-image @ docker://hello-world@sha256:18a657d0cc1c7d0678a3fbea8b7eb4918bba25968d3e1b0adebfa71caddbc346.
Checking if manifest is already uploaded
Remote image not found, getting its info from local registry.
Image not found locally. Passing path directly to skopeo.
Running Skopeo
:: time="2024-08-26T18:39:59Z" level=fatal msg="Error loading trust policy: open /etc/containers/policy.json: no such file or directory"
Error while running /snap/charmcraft/x1/libexec/charmcraft/skopeo (return code 1)
Full execution log: …
```
=> fix(2.7): allow skopeo to use an insecure policy

.github/renovate.json5
Provided this works properly I'll be upstreaming to starbase.
=> chore(renovate): always update pyright on its own

.github/renovate.json5
This is just until we no longer need Windows CI
=> chore(renovate): ignore tox-gh updates

.github/workflows/publish-pypi.yaml
The publish workflow is failing because it doesn't get git tags
=> ci: get tags for automatic publish

charmcraft/charm_builder.py, tests/test_charm_builder.py, tests/unit/utils/test_package.py
The previous version wasn't installing pip if it was already in the venv.
This is the hotfix for 3.x, while https://github.com/canonical/charmcraft/pull/1891 is the hotfix for 2.x.
Fixes #1456
CRAFT-2538
=> fix(charm_builder): force-install pip

.github/workflows/tests.yaml, charmcraft/services/provider.py, pyproject.toml, tests/conftest.py, tests/integration/services/conftest.py, tests/integration/services/test_package.py, tests/integration/services/test_provider.py, tests/unit/services/test_provider.py
Locks the shared cache directory to prevent concurrency issues.
Fixes #1845
CRAFT-3313
=> fix: lock shared cache directory

.gitignore, charmcraft/linters.py, tests/integration/commands/test_analyse.py, tests/integration/ops-main-linter-charms/negative/charmcraft.yaml, tests/integration/ops-main-linter-charms/negative/dispatch, tests/integration/ops-main-linter-charms/negative/metadata.yaml, tests/integration/ops-main-linter-charms/negative/src/charm.py, tests/integration/ops-main-linter-charms/smoke/charmcraft.yaml, tests/integration/ops-main-linter-charms/smoke/dispatch, tests/integration/ops-main-linter-charms/smoke/metadata.yaml, tests/integration/ops-main-linter-charms/smoke/src/charm.py, tests/test_linters.py
Jira: https://warthogs.atlassian.net/browse/CHARMTECH-223
Parent: https://warthogs.atlassian.net/browse/CHARMTECH-219
The idea is to validate that the charm initialises the operator framework correctly:
- charmcraft analyse would validate the presence of the `ops.main(...)` call with this PR
- any conceivable import style is supported
- ops library type hints are improved https://github.com/canonical/operator/pull/1345
- charmers will no longer need to slap `# type: ignore` on the call
- we'll be relying on charmers' static type analysis to ensure correct arguments to `ops.main`
=> feat: validate ops.main() call for operator framework charms

docs/reference/changelog.rst
Quick link to the changelog: https://canonical-charmcraft--1942.com.readthedocs.build/en/1942/reference/changelog/#id1
=> docs(changelog): add 2.7.4 to changelog

docs/conf.py, docs/explanation/index.rst, docs/explanation/lifecycle.rst, docs/reference/index.rst, docs/reference/parts.rst, docs/reference/plugins/index.rst, docs/reuse/links.txt, pyproject.toml
This brings in the common documentation sets from craft-parts and adds some of the pages. It mostly exists to enable my next PR, where I'll document the `python` and `poetry` plugins.
=> feat(docs): add craft-parts common documentation

pyproject.toml, requirements-dev.txt, requirements.txt, tests/spread/smoketests/parallel-install/charmcraft.yaml, tests/spread/smoketests/parallel-install/task.yaml
=> fix: make charmcraft work with snap parallel installs

charmcraft/templates/init-fastapi-framework/src/charm.py.j2
Fix bug in fastapi-framework. The import was incorrect, as it is `paas-charm` instead.
=> fix: fastapi-framework import typo

snap/hooks/configure, snap/hooks/remove
On recent Ubuntu systems, "lxc" might be "/usr/sbin/lxc", which is provided by the "lxd-installer" package and will install the LXD snap if it's not installed. This installation can then take a long time if the store is having issues.
For the purposes of the configure and remove hooks we *don't* want to install LXD just to check that it has no stale images, so update the hooks to do some early detection and bail out if LXD is not installed.
Fixes #1982
=> fix(snap): check if LXD is actually installed

charmcraft/parts/plugins/_poetry.py, charmcraft/parts/plugins/_python.py, charmcraft/utils/__init__.py, charmcraft/utils/parts.py, tests/integration/parts/plugins/test_poetry.py, tests/integration/parts/plugins/test_python.py
Fixes #1966
The lib64 directory exists as a symbolic link in virtual environments for historic reasons, but is not necessary.
This prevents the charm from packing it twice (due to Python's inability to put symlinks into zip files).
=> fix(python,poetry): remove duplicate files in the charm

docs/howto/charm-to-poetry.rst, docs/howto/charm-to-python.rst, docs/howto/index.rst, docs/index.rst, docs/reference/plugins/python_plugin.rst
This adds howto guides to switch from the charm plugin to the python and poetry plugins.
=> docs: add howto guides for switching from the charm plugin

.github/workflows/tests.yaml, charmcraft/templates/init-kubernetes/spread.yaml.j2, charmcraft/templates/init-machine/spread.yaml.j2, charmcraft/templates/init-simple/spread.yaml.j2
The existing default templates generate a charm that doesn't have any tests available on Noble systems. I didn't touch the definition for github, as I'm not sure whether there are limitations of what can be run there.
=> fix: default support to include 24.04

charmcraft/dispatch.py
Fixes #1995
Follow-up to #1972
=> fix(dispatch): fix the dispatch script

charmcraft/parts/plugins/_reactive.py, tests/unit/parts/plugins/test_reactive.py
While a user could previously have added `--verbose` to `reactive-charm-build-arguments`, this automatically adds `--verbose` if the user hasn't specified a log level.
The verbose text gets handled by craft-cli anyway, but this changes the default so the text gets added to the log.
Spread test failures are unrelated: https://github.com/canonical/charmcraft/issues/2023
=> feat(reactive): run charm build in verbose mode

requirements-dev.txt
Fixes the poetry plugin
NOTE: main removed `requirements.txt`, but `requirements-dev.txt` still exists for some workflows. `uv.lock` already has the correct craft-parts.
=> build(deps): update craft-parts

.github/workflows/spread.yaml, .github/workflows/tests.yaml
Ubuntu version shouldn't matter since we're spinning up a container, so we just need to ensure that it's on amd64 because the tests that use these built snaps run on amd64.
=> ci: build the snap on self-hosted runners

.github/workflows/spread-large.yaml
The only reason this would be different is if there happened to be a commit to main that hasn't pushed to edge yet, but that would be very rare and is not worth the extra time we spend building the snap.
=> ci: use charmcraft from the store for weekly spread runs

charmcraft/services/store.py, tests/unit/services/test_store.py
When a charm lib doesn't exist on charmhub, charmhub itself gives us a hard to use error. This is replaced with a more useful message.
Fixes #1754
CRAFT-3353
=> fix(store): nicer error message when getting nonexistent libs

.gitignore, common.mk, docs/reference/changelog.rst, docs/reference/plugins/python_plugin.rst
I figured I'd get an early start on this so it's not a last-minute thing.
=> docs: prepare 3.3 changelog

charmcraft/utils/parts.py, tests/unit/parts/plugins/test_poetry.py, tests/unit/parts/plugins/test_python.py
Including `bin/activate` in the virtual environment will make debugging much easier (charm developers can easily run Python code using the charm's virtual environment to debug issues)
=> Fix & always include bin/activate in python & poetry plugin

charmcraft/parts/plugins/_charm.py, tests/unit/parts/plugins/test_charm.py
This isn't needed for Red Hat based distributions as python3-devel includes the necessary packages
Fixes #2023
CRAFT-3788
=> fix: include libffi-dev in charm part build-packages

.github/workflows/tests.yaml
This allows running snap tests while the store is still processing the snap to publish to a branch.
=> ci: separate snap build and PR publish jobs

charmcraft/application/commands/analyse.py, charmcraft/application/commands/extensions.py, charmcraft/application/commands/store.py, charmcraft/charm_builder.py, charmcraft/extensions/_utils.py, charmcraft/instrum.py, charmcraft/store/models.py, charmcraft/store/store.py, charmcraft/utils/yaml.py, pyproject.toml, tests/integration/commands/test_init.py, tests/unit/commands/test_lifecycle.py, tests/unit/commands/test_store.py, tests/unit/services/test_charmlibs.py, tests/unit/services/test_package.py, tests/unit/services/test_store.py, tests/unit/test_parts.py
This bumps two pyright warnings to errors and fixes those errors
=> style(type): make pyright stricter

tests/test_infra.py
The copyright header test would scan any .py source file, but sometimes files do not need a Canonical copyright header.
As an example, in https://github.com/canonical/charmcraft/pull/2050, a spread test was added that contained a directory generated by `uv init`. This command makes a pretty minimal Python hello world, and the copyright header test was failing it.
=> test: enable ignoring of fileglobs

common.mk
I messed this up when I removed the pyright dep from uv
=> fix(common.mk): get upstream setup-lint

charmcraft/models/project.py, charmcraft/services/package.py, pyproject.toml, requirements-dev.txt, tests/integration/commands/test_expand_extensions.py, tests/integration/sample-charms/actions-included/expected.yaml, tests/integration/sample-charms/actions-separate/expected.yaml, tests/integration/sample-charms/basic-platforms/expected.yaml, tests/integration/sample-charms/config-included/expected.yaml, tests/integration/sample-charms/config-separate/expected.yaml, tests/spread/smoketests/multi-base/all/charmcraft.yaml, tests/spread/smoketests/multi-base/all/expected-charms.txt, tests/spread/smoketests/multi-base/basic/charmcraft.yaml, tests/spread/smoketests/multi-base/basic/expected-charms.txt, tests/spread/smoketests/multi-base/one-platform/arguments.txt, tests/spread/smoketests/multi-base/one-platform/charmcraft.yaml, tests/spread/smoketests/multi-base/one-platform/expected-charms.txt, tests/spread/smoketests/multi-base/task.yaml, tests/unit/models/test_project.py, tests/unit/services/test_package.py, uv.lock
Adds support for multi-base recipes with the `platforms` keyword.
Internally, this moves to a new practice where the application stops modifying project data before passing the it to craft-platforms.  This will ensure consistent processing by charmcraft and by launchpad.
Documentation is coming soon via https://github.com/canonical/craft-platforms/issues/75 and https://github.com/canonical/charmcraft/issues/2009.
To summarize the usage, `base` and `build-base` are removed from the project and the base is encoded into the platform.
Platforms can be defined in a shorthand notation:
```yaml
platforms:
ubuntu@22.04:amd64:
ubuntu@24.04:amd64:
```
Or they can be defined in standard form:
```yaml
platforms:
jammy:
build-on: [ubuntu@22.04:amd64]
build-for: [ubuntu@22.04:amd64]
noble:
build-on: …
```
=> feat: support multi-base recipes

docs/howto/charm-to-poetry.rst
--with is required for optional and non-optional dependencies
see https://github.com/python-poetry/poetry-plugin-export/pull/212 and https://github.com/python-poetry/poetry-plugin-export/issues/299
corresponding PR in https://github.com/canonical/craft-parts/pull/946
=> docs: fix poetry-with description

charmcraft/services/package.py, tests/spread/smoketests/multi-base/basic/expected-charms.txt, tests/spread/smoketests/multi-base/one-platform/expected-charms.txt, tests/unit/services/test_package.py
Multi-base charms may have colons in their platform name. These get converted to hyphens because some environments don't allow colons in filenames.
Fixes #2057
=> fix: replace colons with hyphens in charm names

.pre-commit-config.yaml, charmcraft/utils/platform.py, pyproject.toml, tests/test_jujuignore.py
This handles the cases where lint starts failing with ruff 0.9.0.
=> style: update to ruff 0.9.0 formatting

charmcraft/models/project.py, tests/integration/commands/test_expand_extensions.py, tests/integration/commands/test_pack.py, tests/integration/conftest.py, tests/integration/sample-charms/actions-included/charmcraft.yaml, tests/test_infra.py, tests/unit/models/invalid_charms_yaml/platforms-empty-parts.yaml, tests/unit/models/invalid_charms_yaml/platforms-no-parts.yaml, tests/unit/models/test_project.py, tests/unit/services/test_package.py, tests/unit/test_preprocess.py
There were previously edge cases where a platform charm could be declared but the lack of a `parts` key wouldn't be caught. This now enforces at least one part.
Fixes #2055
CRAFT-3851
=> fix(models/project): make no parts error explicit

charmcraft/application/commands/test.py
The test command is experimental and was not intended to reach stable
releases. Place a notice on command help and execution. This command
will be removed and replaced by the final implementation that will
exist in craft-application.
=> fix(commands/test): add experimental notice to command

charmcraft/application/commands/store.py, docs/reference/changelog.rst, tests/unit/commands/test_store.py
This takes care of the edge case where you want to re-publish the same library version with the same content. In this case we don't create a new revision on the store, but we also don't cause an error.
Changelog link: https://canonical-charmcraft--2106.com.readthedocs.build/en/2106/reference/changelog/#id1
Fixes #1981
=> fix: exit with 0 if re-publishing the same library

.github/workflows/spread-docs.yaml, docs/howto/code/flask-async/task.yaml, docs/tutorial/code/flask/task.yaml, spread.yaml, tests/spread/tools/prepare.sh
This adds a CI workflow for spread testing flows in the documentation. In so doing I needed to adjust the documentation spread tasks to pass on Google's runners too.
CRAFT-3798
=> ci(docs): spread test documentation

docs/howto/manage-bundles.rst, docs/howto/manage-resources.rst, docs/reference/files/bundle-yaml-file.rst, docs/reference/files/charmcraft-yaml-file.rst
Depends on ~https://github.com/juju/juju/pull/18788~ https://github.com/juju/juju/pull/18790.
=> docs: fix broken references to juju docs

docs/howto/index.rst, docs/howto/manage-12-factor-app-charms.rst, docs/howto/manage-channels.rst, docs/howto/manage-charmcraft.rst, docs/howto/manage-charms.rst, docs/howto/manage-tracks.rst
This PR adds a few anchors that will be used through intersphinx in the Ops docs.
The PR also changes a couple of titles and adds some content. Also fixes a weird rendering error.
Note: 
- The reason I've changed "Set up Charmcraft" to "Manage Charmcraft", as it used to be, is because that's the pattern we follow everywhere in Juju-world docs, the reason being that that docs doesn't just cover setup but should also cover upgrade and uninstall. I've added some content to that effect as well.
- For charm naming best practices we should at some point enhance that note to reflect, in streamlined fashion, all the crucial bits from https://discourse.charmhub.io/t/charm-naming-guidelines/5364#naming-charms-1 (this old Discourse post can then be discarded).
=> docs: add anchors and fix a few small things

charmcraft/services/provider.py, tests/integration/services/test_provider.py
Fixes #2125
CRAFT-4037
Test failures are unrelated. I will be putting up a separate PR to fix those. Reporter has confirmed that [the fix works for them](https://github.com/canonical/charmcraft/issues/2125#issuecomment-2630600486)
Tests will pass when I rebase on https://github.com/canonical/charmcraft/pull/2137
=> fix(provider): ensure /root/.cache exists

docs/howto/build-guides/pack-a-hooks-based-charm-with-charmcraft.rst, docs/howto/manage-12-factor-app-charms.rst, docs/howto/manage-charms.rst, docs/howto/manage-libraries.rst, docs/howto/manage-resources.rst
Corrects the remaining **See next** and **See also** link text for Ops Library targets.
=> docs: align ops links formatting

snap/snapcraft.yaml
=> fix(completion): correct path to build bash completion on non-amd64

docs/conf.py
Add a "Give feedback" button to the top of the RTD site that links the user to a GitHub issue form to describe any feedback they have about a particular docs page.
=> feat(docs): add feedback button

pyproject.toml, tests/spread/commands/init-extensions/task.yaml, tests/spread/commands/init-extensions/tests/unit/test_charm.py, tests/spread/commands/init-extensions/tox.ini
To avoid issues like https://github.com/canonical/charmcraft/pull/1970, a scenario test has been added to the spread test for the `{go,flask,fastapi,django}-framework` init profiles.
This test is a [scenario test (unit test)](https://juju.is/docs/sdk/write-a-functional-test-for-a-charm-with-scenario), that uses the `paas-charm` library and runs a pebble ready event. The real goal of the test is that there are no syntax errors or wrong imports in the init template.
=> Create scenario tests for init templates

docs/release-notes/charmcraft-3.4.rst, uv.lock
Two commits to rebase: First updates craft-providers, second updates the release notes.
=> chore: prepare 3.4.3 release

charmcraft/extensions/app.py
Add the new `*-secret-key-id` charm configurations to Flask, Django, Golang, and FastAPI framework charms.
The `*-secret-key-id` configuration serves a similar purpose as the old `*-secret-key` configuration but instead accepts Juju secrets, providing a more secure way to pass sensitive information like secret keys.
This change is backward-compatible with deployments on Juju 3, as the old configuration still exists but takes lower precedence. However, it might not be compatible with Juju 2, as Juju 2 does not support Juju secrets.
=> feat: add *-secret-key-id charm configuration for flask, django, golang and fastapi framework charms

docs/howto/manage-charms.rst
The HTG Manage charms / Publish > Release example did not include resources, although (1) resources had been mentioned previously and (2) the way to attach them at release time is easy to forget. This has resulted in an issue even for an otherwise expert user: https://github.com/canonical/charmcraft/issues/2171 This PR fixes that. (It also makes the name of the charm the same across all the examples in the Publish section.)
@erik78se Thanks for the example output for releasing with a resource. 
Fixes #2171
=> docs: update release step with resource details

docs/howto/manage-libraries.rst, docs/howto/migrate-plugins/charm-to-uv.rst, docs/howto/migrate-plugins/index.rst, docs/reference/plugins/uv_plugin.rst
Adds a how-to for migrating to the uv plugin. It's based on the poetry plugin page.
Drive-by: typo fix
https://canonical-charmcraft--2156.com.readthedocs.build/en/2156/howto/migrate-plugins/charm-to-uv/
=> docs(how-to): add how-to migrate to uv

snap/snapcraft.yaml
This should only affect armhf, so it's good if this build succeeds:
https://launchpad.net/~lengau/lengau-craft-remote-build/+snap/snapcraft-charmcraft-65ef4d96be7404bf850a3e56b29033fa/+build/2726730
=> fix(snap): fix build on 32-bit platforms

charmcraft/extensions/app.py, docs/reference/extensions/django-framework-extension.rst, docs/reference/extensions/fastapi-framework-extension.rst, docs/reference/extensions/flask-framework-extension.rst, docs/reference/extensions/go-framework-extension.rst, docs/reuse/reference/extensions/non_optional_config.rst, tests/extensions/test_app.py
This PR is related to 12 Factor [Block on missing required config PR](https://github.com/canonical/paas-charm/pull/42)
Some applications require certain config options to run and would crash if these options are not provided. To prevent this, we need to add an optional field to the config options and block the charm if a config option marked as non-optional has not been provided with a message that explains which config options are missing.
To stay backward compatible the default value for the optional field will be true.
Since it doesn’t make sense for config options that are non-optional to have a default value, charmcraft will look for this condition at pack time and error out.
Adds a check for non-optional options with default values and throws `ExtensionError` when found.
Adds …
=> feat(extension): Block on missing required config

docs/tutorial/code/django/task.yaml, docs/tutorial/kubernetes-charm-django.rst
Some specific fixes to the Django tutorial:
* Don't need to explicitly have `python3 manage.py`. Django developers are more used to `./manage.py` instead. I have updated the tutorial and `task.yaml` file. 
* Any reference to `/django-hello-world` in text has been updated to `~/django-hello-world`.
* Updated indentation in a code snippet that was rendering incorrectly.
Additional reviewers: @jdkandersson
=> docs: maintain Django tutorial

charmcraft/templates/init-kubernetes/charmcraft.yaml.j2, charmcraft/templates/init-machine/charmcraft.yaml.j2, charmcraft/templates/init-simple/charmcraft.yaml.j2, tests/spread/smoketests/different-dependencies/task.yaml, tests/spread/smoketests/pinned-dependencies/task.yaml
This updates the templates to use the `platforms` notation rather than `bases`. It keeps them building on Jammy for the timebeing though.
CRAFT-4150
Fixes #2167
=> feat(templates): change the templates to use platforms notation

docs/tutorial/kubernetes-charm-django.rst, docs/tutorial/kubernetes-charm-fastapi.rst, docs/tutorial/kubernetes-charm-flask.rst, docs/tutorial/kubernetes-charm-go.rst
Mostly directory-related maintenance work spanning across all four 12-factor tutorials.
* The "What you'll do" sections are now numbered lists.
* Any mention of the root directory (e.g., `/django-hello-world`) now contains a tilde in front (e.g., `~/django-hello-world`).
* Captions on full code examples now contain captions with explicit reference to the full path (e.g., `app.py` is now `~/flask-hello-world/app.py`). This change did not affect snippets of YAML files, which contain no caption whatsoever.
* Some mentions of `visitors_app.py` were renamed to `app.py` as the `visitors_app.py` naming was due to the multiple Python files needed for the spread tests.
=> docs: 12-factor tutorial maintenance

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/documentation.yaml
Replaces the documentation discourse link with an issue template to help describe documentation requests.
Fixes #2214 
CRAFT-4306
=> chore: add a documentation issue template

charmcraft/application/commands/store.py
This command is deprecated and will be removed in Charmcraft 4.0. Bundle commands will remain available in Charmcraft 3.
CRAFT-4005
=> feat: mark the "promote-bundle" command as deprecated

charmcraft/models/project.py
Bundles are deprecated and will be removed in Charmcraft 4. Charmcraft 3 will remain available for packing bundles.
CRAFT-4006
Lint issues are fixed in https://github.com/canonical/charmcraft/pull/2229
=> feat: mark bundles as deprecated

docs/tutorial/kubernetes-charm-django.rst, docs/tutorial/kubernetes-charm-fastapi.rst, docs/tutorial/kubernetes-charm-flask.rst, docs/tutorial/kubernetes-charm-go.rst
Three updates that expand over all four tutorials. These changes were suggested from one or more UX sessions. 
Summary of changes:
1. If the user needs to open rockcraft.yaml or charmcraft.yaml to update the architecture to `arm64`, have them also comment out `amd64`. While there's no harm or issue with having both architectures available, for novice users, this change will eliminate any possible concern or worry over including both architectures in the YAML file(s).
2. Provide more explanation and reassurance about the web app entering a blocked state when adding the PostgreSQL database.
3. Rephrase the "tear things down" section to tell the users that they can just delete the whole instance if they're not going to keep the VM. 
Additional reviewer: @jdkandersson
=> docs: Tutorial updates

CONTRIBUTING.md
I was working through the instructions in CONTRIBUTING.md but wasn't able to run `python -m charmcraft`. Then I realised that I needed to first activate the virtual environment created by `make setup`. That's probably obvious to many, but it tripped me up :slightly_smiling_face: 
This PR adds an explicit command for activating the virtual environment.
=> docs: add venv activation to the contribution instructions

docs/conf.py, docs/howto/manage-web-app-charms/integrate-web-app-charm.rst, docs/howto/manage-web-app-charms/use-web-app-charm.rst, docs/reference/extensions/django-framework-extension.rst, docs/reference/extensions/flask-framework-extension.rst
* Add a new section, "Use observability" on how to access the dashboards and view application logs.
* Tweak titles of other usage-related how-to's in the same file.
* Add a section target on "Integrate with observability".
* Based on the PR review, updated the Flask and Django reference pages.
Additional reviewer: @jdkandersson
=> docs: Add 12-factor how-to on using observability

docs/tutorial/kubernetes-charm-django.rst, docs/tutorial/kubernetes-charm-fastapi.rst, docs/tutorial/kubernetes-charm-flask.rst, docs/tutorial/kubernetes-charm-go.rst
Updates to the 12-factor tutorials that affect all four tutorials.
* Add a tip admonition to let the user know about `charmcraft expand-extensions`. This has been a repeated ask from UX research participants.
* Convert the `juju status` admonition to a tip to recommend that users start a `juju status` session in a new tab to monitor their deployment. This prepares the user for a successful deployment setup. 
* Update the terminal output for `rockcraft pack` to use a generic architecture stand-in. This indicates that the architecture plays an active role in defining the rock. 
* Mention that subsequent `charmcraft pack` and `rockcraft pack` commands are faster after the initial packing. This has been a repeated ask from UX research participants. 
* Condense text about adding an …
=> Docs: Update 12-factor tutorials

docs/reuse/tutorial/setup_edge.rst, docs/reuse/tutorial/setup_stable.rst, docs/tutorial/kubernetes-charm-django.rst, docs/tutorial/kubernetes-charm-fastapi.rst, docs/tutorial/kubernetes-charm-flask.rst, docs/tutorial/kubernetes-charm-go.rst
Updates to the 12-factor tutorials that affect the reusable setup files and all four tutorials. Some of these changes were suggested by @evildmp in https://github.com/canonical/charmcraft/issues/2235
* Updated the `setup_edge.rst` file to install the `latest/edge` channel of Rockcraft.
* Removed an admonition block in the Django tutorial that warned users about using an older version of Rockcraft. 
* Removed any mentions of "easily" in the tutorials.
* Removed `touch` from the instructions and ask users to instead open the new file directly with `nano`.
* Removed the admonition block warning users about the Charmcraft version.
=> Docs: Updated 12-factor tutorials

docs/howto/manage-web-app-charms/use-web-app-charm.rst
Add a troubleshooting section into the "Use a 12-factor app charm" page that covers how a user would access logs (Juju, application, MicroK8s) and how the user can SSH into the Juju container for more in-depth debugging. 
Additional reviewers: @javierdelapuente @jdkandersson
=> docs: add 12-factor troubleshooting section

docs/conf.py
The `latest` build on Juju docs is now private, so we need to switch to this
=> chore(docs): switch the docs to link to Juju 3.6

docs/tutorial/kubernetes-charm-django.rst, docs/tutorial/kubernetes-charm-fastapi.rst, docs/tutorial/kubernetes-charm-flask.rst, docs/tutorial/kubernetes-charm-go.rst
Six updates proposed by @evildmp in https://github.com/canonical/charmcraft/issues/2235 that affect all four of the 12-factor tutorials.
* Converted first note admonition into a normal paragraph.
* Updated the ambiguity of "Ensure that platforms includes the architecture of your host." by using the suggestion "Platforms must match the architecture of your host."
* Updated the instruction to edit `rockcraft.yaml` using the suggestion. 
* Removed an explicit reference to AMD64 architecture at the Juju model constraint step to let the user build up muscle memory. Architecture is still mentioned because that's what the command is explicitly doing.
* (Django tutorial only) Updated "The generated Django app doesn’t come with an app" to reference the Django *project* instead.
* (Django tutorial …
=> Docs: 12-factor tutorial updates

docs/howto/manage-charms.rst
Improve charm docs guidance to include smaller/bigger charm docs. 
Add links to the charm docs exemplars.
This is a part of the [Epic](https://warthogs.atlassian.net/browse/DOCPR-948) to Standardise charm documentation by creating exemplars of good.
=> docs: add charm docs exemplars links

docs/howto/manage-charms.rst
Fixed links syntax in the Add docs section of Manage charms page. I've tested it locally, so it should work this time.
Added a link to the Charmhub's Discourse instance.
=> docs: hotfix for links syntax for charm docs examples

docs/conf.py
Local documentation builds currently fail due to the following warnings:
```bash
Warning, treated as error:
/home/ecoldi/Projects/Canonical/charmcraft/docs/reuse/reference/extensions/integrations.rst:125:Undefined substitution referenced: "juju_integrate_postgresql".
make: *** [common.mk:224: docs] Error 2
```
```bash
Warning, treated as error:
/home/ecoldi/Projects/Canonical/charmcraft/docs/common/craft-parts/reference/plugins/jlink_plugin.rst:document isn't included in any toctree
make: *** [common.mk:224: docs] Error 2
```
This absolute behemoth of a PR resolves this issue by adding the guilty files to the `exclude_patterns` list.
=> docs: resolve local build errors

docs/tutorial/kubernetes-charm-django.rst, docs/tutorial/kubernetes-charm-fastapi.rst, docs/tutorial/kubernetes-charm-flask.rst, docs/tutorial/kubernetes-charm-go.rst
Six updates proposed by @evildmp in https://github.com/canonical/charmcraft/issues/2235 that affect all four of the 12-factor tutorials.
* Added a brief explanation of a rock at the beginning of the rock sections.
* (Django tutorial) Before packing the rock, added a note that explains that the user can no longer run or test the app locally due to the changes we made in preparing the app for a PostgreSQL database.
* (FastAPI and Go tutorials) Changed some instances of the mechanical instruction "open" to a functional action "edit" for updating the `charmcraft.yaml` file. This also establishes consistency with the corresponding rock sections.
* Added a `seealso` box to `charmcraft pack` to provide more context to the user.
* Added a brief explanation of a Juju model at the beginning of the …
=> docs: Updates to the 12-factor tutorials

.github/workflows/qa.yaml, Makefile
I got a query from @cbartz about why we're using hosted runners for Charmcraft QA rather than GH-hosted runners, as Platform Engineering would prefer we use GH-hosted runners when possible for public repos. This makes this change.
Note that this only affects linux runners on the QA workflow.
=> ci: run tests on GH-hosted runners

.github/workflows/spread-docs.yaml, .github/workflows/spread.yaml, spread.yaml
This sets up the spread test jobs to split the tests by system. It automatically generates the list of systems based on the spread file in order to reduce re-runs for flaky tests.
=> ci: split spread tests by system

.github/workflows/schema.yaml
This was breaking on Jammy due to apt issues, but there's no reason not to just roll to the latest LTS.
=> ci: use Ubuntu latest for schema diff

common.mk, docs/conf.py, pyproject.toml, uv.lock
* Adds `sphinx-sitemap` as a docs dependency
* Modifies `conf.py` to generate a sitemap during build
* Switches local builds to the `dirhtml` builder
[sitemap.xml](https://canonical-charmcraft--2323.com.readthedocs.build/2323/sitemap.xml)
=> build(docs): add sphinx sitemap

docs/tutorial/kubernetes-charm-fastapi.rst
Closes [Charmcraft FastAPI tutorial: Add structure to sections #208](https://github.com/canonical/open-documentation-academy/issues/208)
- Inserted "The development cycle" section after "Deploy the FastAPI app", and split the existing content under new subheadings.
- Added an "Introduction" heading below the main title, and changed the subsequent two headings into subheadings to match Django's tutorial structure
- Fixed typo: "Deplyoing" -> "Deploying". 
- Changed "Hello World" to "Hello, world!" for consistency inside the FastAPI tutorial, and alignment with the Django tutorial.
=> docs: align FastAPI tutorial structure with Django tutorial

charmcraft/templates/init-kubernetes/README.md.j2, charmcraft/templates/init-machine/README.md.j2
Inspired by https://github.com/canonical/charmcraft/pull/2350, this PR makes some fixes in the template README files for the `kubernetes` and `machine` profiles.
Fixes:
- Talk about `charmcraft.yaml` instead of `metadata.yaml`
- Use the (dynamic) charm name for the package name instead of `operator-template`
- Replace links to https://juju.is/docs/sdk by https://documentation.ubuntu.com/juju/3.6/howto/manage-charms/
=> fix(templates): update out-of-date parts in template README files

.github/workflows/spread.yaml, .github/workflows/tests.yaml, .github/workflows/tics.yaml
We have a number of tests that take a long time (and a lot of energy) to run, and we don't need to run those on every single PR. This sets them not to run when the *only* changes are on certain paths that cannot affect them.
=> ci: be more selective about when we run expensive tests

docs/release-notes/charmcraft-3.5.rst
Rendered: https://canonical-ubuntu-documentation-library--2414.com.readthedocs.build/charmcraft/2414/release-notes/charmcraft-3.5/#fixed-bugs-and-issues
Test failures are ephemeral.
=> chore: Release 3.5.3

charmcraft/application/commands/store.py
Closes #2375. This PR just removes the example given, as similar tabulated commands do not have output examples (see [snapcraft status](https://documentation.ubuntu.com/snapcraft/stable/reference/commands/status/)) and anything beyond simple text is pretty unstable to use in our help messages.
=> docs: remove command output example
