charmcraft/__init__.py
0.1.1 was already taken so we can't release it :-(
=> bump version for 0.1.2

MANIFEST.in, completion.bash, snap/snapcraft.yaml
=> a first pass at tab completion for the snap (hand-crafted)

charmcraft/commands/build.py, tests/commands/test_build.py
After this, the code ALWAYS handles Path objects.
=> Totally avoid dealing with paths as strings.

charmcraft/commands/store/client.py, requirements.txt, tests/commands/test_store_client.py
This is in preparation for a next branch about the whole Upload command.
=> Support for pushing bytes to the Storage.

charmcraft/commands/store/__init__.py, charmcraft/commands/store/store.py, charmcraft/main.py, tests/commands/test_store_api.py, tests/commands/test_store_commands.py
This is the next branch after #75
=> Store upload

HOWTO_RELEASE.md, charmcraft/version.py
Left undone: changing IRC channel topic
=> Release 0.3.0

charmcraft/commands/build.py, tests/commands/test_build.py
Included here:
- put the 'hooks' dir as a constant
- introduced a 'relativise' helper, that will be used in the next branch 
- added a verification in the build command line: the entry point must be inside the project
=> Some changes in preparation for big "include everything but jujuignored" branch.

charmcraft/commands/build.py, tests/commands/test_build.py
Setting it to "Draft" because there are some remaining FIXMEs, for which I'm waiting for PR #99 to land.
=> Include everything but what is explicity ignored to Juju.

charmcraft/templates/init/README.md.j2
=> Fix the 'pip install' command from the template README

charmcraft/cmdbase.py, charmcraft/commands/build.py, charmcraft/commands/init.py, charmcraft/commands/store/__init__.py, charmcraft/commands/version.py, charmcraft/main.py, tests/commands/test_version.py, tests/test_cmdbase.py
Also I stopped doing a runtime check of the command integrity, in favor of a test-time verification.
The program output is not tested as it's handled automatically by argparse (it will be properly verified by our tests when we move to the custom-generated helps, in the short future).
@chipaca: feel free to push a commit over this PR for changes in the texts (that will easier for both of us than a bunch of changes).
=> Added an "overview" attribute to each command, with the long help descriptions.

charmcraft/templates/init/src/charm.py.j2, charmcraft/templates/init/tests/test_charm.py.j2
Whooops.
Fixes: #141
Thanks to @narindergupta for bringing this to our attention.
=> fix the action generated by 'charmcraft init'

README.md
=> explain how to run the project from git

charmcraft/commands/build.py, charmcraft/commands/init.py, charmcraft/commands/store/__init__.py, charmcraft/commands/version.py, tests/commands/test_build.py, tests/commands/test_store_commands.py, tests/test_help.py, tests/test_main.py
This includes the command ones and command's parameters ones.
Also fixed some output messages as per UX dept. suggestion.
This is part of the [big adjust help process](https://github.com/canonical/charmcraft/pull/153).
=> Improved short help messages.

charmcraft/helptexts.py, tests/factory.py, tests/test_help.py
Not integrated yet, this is part of the [big adjust help process](https://github.com/canonical/charmcraft/pull/153).
=> Text builders for simple usage, detailed help, and command help.

charmcraft/commands/store/__init__.py, completion.bash, tests/commands/test_store_commands.py
=> make revision a positional argument to release

charmcraft/commands/store/__init__.py, tests/commands/test_store_commands.py
This function is not used yet (but adding first code that uses it makes the branch too large).
This is part of [all libraries related functionality branch](https://github.com/facundobatista/charmcraft/tree/charmlibs-draft).
=> Added function to load libraries information.

charmcraft/commands/init.py, charmcraft/commands/store/__init__.py, charmcraft/commands/store/store.py, charmcraft/commands/utils.py, charmcraft/main.py, charmcraft/templates/charmlibs/new_library.py.j2, tests/commands/test_store_api.py, tests/commands/test_store_commands.py, tests/factory.py
This is the second cut of the big [charmlibs draft](https://github.com/facundobatista/charmcraft/tree/charmlibs-draft).
=> Support to create a library, first step in all the lifecycle.

CODE_OF_CONDUCT.md, HOWTO_RELEASE.md, README.md, charmcraft/commands/build.py, charmcraft/commands/init.py, charmcraft/commands/store/__init__.py, charmcraft/commands/version.py, charmcraft/helptexts.py, charmcraft/main.py, charmcraft/templates/charmlibs/new_library.py.j2, charmcraft/templates/init/README.md.j2, tests/commands/test_store_commands.py, tests/test_help.py
Lots of text work, I tried not to change anything that might break tests but the occasional %s might have slipped through :)
=> Small text cleanups for README and charmcraft help

charmcraft/config.py, requirements.txt, tests/test_config.py
Not used from the rest of the system, yet, to keep the PR reviewable.
=> Configuration schema and support classes.

charmcraft/config.py, charmcraft/main.py, charmcraft/utils.py, tests/commands/test_utils.py, tests/test_config.py, tests/test_help.py, tests/test_main.py
Note the config is still not used (just trying to keep branches small).
=> Add --project-dir general arg, and load config from specified directory.

charmcraft/commands/store/__init__.py, charmcraft/commands/store/store.py, tests/commands/test_store_api.py, tests/commands/test_store_commands.py
I had doubts about how to present the errors to the user, I just followed (IIUC) what snapcraft does.
Fixes #78.
=> Show to the user the returned error in case of rejected upload.

charmcraft/commands/store/__init__.py, completion.bash, tests/test_infra.py
I took the opportunity to bring these improvements for autocompletion because now there is a test that verifies that all commands are included there. This is mainly to catch the case where a command is added and autocompletion is forgotten, but also has the nice side effect of catching involuntary command names changes, as the one this branch is fixing.
=> Back to 'status' for the command, and autocompletion improvement.

charmcraft/commands/store/__init__.py, charmcraft/commands/store/store.py, tests/commands/test_store_api.py, tests/commands/test_store_commands.py
This is the final PR of the sequence. Fixes #176.
=> Support resources when showing charm status.

charmcraft/commands/store/client.py, charmcraft/utils.py, tests/commands/test_store_client.py, tests/test_utils.py
This will be used later from the charm and bundle builders.
This PR is part of [this draft](https://github.com/canonical/charmcraft/pull/279).
=> Added a helper to create a manifest

charmcraft/utils.py, tests/test_utils.py
This PR should land *before* #281 (which I just converted to "draft").
=> Have 'bases' in the manifest, with the translated architecture.

charmcraft/templates/charmlibs/new_library.py.j2, charmcraft/templates/init/actions.yaml.j2, charmcraft/templates/init/config.yaml.j2, charmcraft/templates/init/src/charm.py.j2, charmcraft/templates/init/tests/test_charm.py.j2
Added links to the SDK docs throughout as discussed @facundobatista :smile:
=> Add doc links

charmcraft/config.py, tests/test_config.py
=> config: improve error messages for extra & missing fields

charmcraft/config.py, tests/test_config.py
Support short-form bases, where a base implies the long-form
base configuration equivalent of:
```
- build-on: [<base>]
run-on: [<base>]
```
=> config: add short-form bases support (CRAFT-11)

charmcraft/commands/store/registry.py, tests/commands/test_store_registry.py
Also improved some imports and de-duplicated a constant (bad merge in previous branches).
=> Added a small upload_blob helper (CRAFT-237)

charmcraft/commands/store/registry.py, tests/commands/test_store_registry.py
Also improve the `assert_response_ok` function to better detect if the response is JSON, and added a bunch of type hints.
=> Added the upload_from_local functionality to ImageHandler (CRAFT-239)

charmcraft/commands/build.py, tests/commands/test_build.py
metadata.yaml is read during handle_package().  Instead, read and
parse the metadata on Builder's init, allowing for re-use across
the class. Add explicit error if metadata.yaml is missing and add
test case (Charmcraft currently fails with FileNotFoundError).
=> build: require metadata.yaml and parse on Builder init (CRAFT-301)

charmcraft/commands/build.py, charmcraft/commands/init.py, charmcraft/commands/pack.py, charmcraft/commands/store/__init__.py, charmcraft/commands/store/client.py, charmcraft/logsetup.py, charmcraft/utils.py, tests/commands/test_pack.py, tests/commands/test_store_client.py, tests/commands/test_store_commands.py, tests/test_logsetup.py, tests/test_utils.py
=> Normalize paths representation (CRAFT-287)

charmcraft/commands/store/store.py, tests/commands/test_store_api.py, tests/commands/test_store_commands.py
This is to later be used by the `status` command.
=> Implement support for Bases in Store layer (CRAFT-298)

charmcraft/providers.py, tests/test_providers.py
=> providers: add get_instance_name() for naming instances (CRAFT-310)

charmcraft/utils.py, tests/test_utils.py
=> utils: introduce confirm_with_user() helper for prompting (CRAFT-336)

charmcraft/providers.py, tests/test_providers.py
Note that this won't prompt the user if stdin does not appear to
be an interactive TTY.
=> providers: prompt user to install LXD if not installed (CRAFT-335)

charmcraft/linters.py, charmcraft/metadata.py, tests/test_linters.py, tests/test_metadata.py
Note that linters are still NOT enforced when packing (will do that in the next branch when I add the --force option to pack anyway).
Also note that this PR depends on the "analint 06" one.
=> Added a linter to verify that the metadata is ok (CRAFT-322).

charmcraft/commands/build.py, charmcraft/commands/pack.py, charmcraft/config.py, charmcraft/parts.py, tests/commands/test_pack.py, tests/test_parts.py
Add the craft-parts bundle plugin and invoke the parts lifecycle from
the bundle packing command.
=> pack: implement bundle plugin (CRAFT-360)

.github/workflows/tests.yaml, charmcraft/providers/_buildd.py, requirements-dev.txt, requirements.txt, setup.py, tests/providers/test_buildd.py, tools/freeze-requirements.sh
Update craft-parts version to 1.0 in package setup and requirements,
and remove unnecessary installation of sudo in provider setup.
=> packaging, providers: update craft-parts to 1.0 (CRAFT-452)

.github/workflows/cla-check.yaml
=> ci: add CLA check (CRAFT-305)

.github/workflows/tests.yaml, windows/AppxManifest.xml, windows/charmcraft.iss, windows/generate-self-signed-cert.ps1, windows/modpath.iss
=> windows: build installers for Windows (CRAFT-21)

charmcraft/commands/store/__init__.py
Added an example of how the output would look like, and how to build a fetch-lib command from that. Fixes #377.
=> Improved the list-lib command's help (CRAFT-508).

charmcraft/cmdbase.py, charmcraft/helptexts.py, charmcraft/main.py, tests/commands/test_analyze.py, tests/commands/test_clean.py, tests/commands/test_init.py, tests/commands/test_pack.py, tests/commands/test_store_commands.py, tests/commands/test_version.py, tests/test_cmdbase.py, tests/test_help.py, tests/test_main.py
This is a **big** branch, but 99% are silly and repetitive test changes.
I'll add comments around real code changes, to flag them.
=> Removed the command group from the command itself to simplify the whole structure (CRAFT-555).

charmcraft/linters.py, tests/test_linters.py
=> Added linters to verify actions.yaml and config.yaml (CRAFT-554).

requirements-dev.txt, requirements.txt
Update craft-parts requirements to version 1.0.3.
=> requirements: update craft-parts to 1.0.3 (CRAFT-577)

requirements-dev.txt, requirements.txt
Update craft-parts dependency to version 1.0.4.
=> requirements: update craft-parts to 1.0.4

charmcraft/commands/store/__init__.py, charmcraft/commands/store/store.py, completion.bash, tests/commands/test_store_api.py, tests/commands/test_store_commands.py
**Note**: this PR depends on the #601 one.
=> Added an export option to login to save the obtained credentials (CRAFT-641).

charmcraft/commands/store/__init__.py, charmcraft/commands/store/store.py, completion.bash, tests/commands/test_store_api.py, tests/commands/test_store_commands.py
**Note**: this PR depends on #601 and #602 .
=> Added restrictive options to login command (CRAFT-640).

charmcraft/commands/store/store.py, tests/commands/test_store_api.py
Define a `allow_login` parameter to the store client decorator so
that the `whoami` command can use it to handle errors without
automatically logging the user in.
Example error messages:
- If no external credentials are used, and the user is not logged in:
```
$ charmcraft whoami
You are not logged in to Charmhub.
```
- If credentials are used, and the response code is 401:
```
$ CHARMCRAFT_AUTH="$(cat ~/creds-expired)" charmcraft whoami
Provided credentials are no longer valid for Charmhub. Regenerate them and try again.
```
=> store: handle store errors in whoami command (CRAFT-701)

.github/workflows/tests.yaml
- Test on all pull requests for this repo
- Update push test to main
=> gha: update workflow triggers

requirements-dev.txt, requirements.txt, tools/freeze-requirements.sh
Forced by [these changes](https://github.blog/2021-09-01-improving-git-protocol-security-github/).
=> Use git+https in the dependencies.

requirements-dev.txt, requirements.txt
=> snap: update craft-store to 2.0.1

charmcraft/linters.py, tests/test_linters.py
=> linters: module name from metadata name

charmcraft/commands/store/__init__.py, tests/commands/test_store_commands.py
=> _get_lib_info should generate importable paths.

HOWTO_RELEASE.md, charmcraft/cmdbase.py, charmcraft/commands/analyze.py, charmcraft/commands/pack.py, charmcraft/commands/version.py, completion.bash, tests/commands/test_analyze.py, tests/commands/test_pack.py, tests/commands/test_version.py, tests/conftest.py, tests/test_main.py
This is the first of two branches, the second will complete the rest of commands that needs this new feature.
=> Added programmatic outputs to all non store-related commands.

charmcraft/commands/store/__init__.py, tests/commands/test_store_commands.py
=> Added programmatic output to resources related commands (CRAFT-1107).

charmcraft/main.py, requirements-dev.txt, requirements.txt, tests/test_main.py
=> Do not expose the logpath when running in managed mode (CRAFT-1035).

charmcraft/commands/build.py, charmcraft/commands/pack.py, charmcraft/deprecations.py, completion.bash, tests/commands/test_build.py, tests/commands/test_pack.py
=> Removed the --requirements option for build and pack commands (CRAFT-787).

charmcraft/linters.py, tests/commands/test_store_commands.py, tests/test_charm_builder.py, tests/test_main.py, tests/test_utils.py
=> many: reword docstrings and code comments

charmcraft/commands/store/__init__.py, tests/commands/test_store_commands.py
=> Improve json format for the status command.

README.md
Same as #805, but reauthored to pass CLA check
=> Update snap install to use --classic

charmcraft/commands/build.py
Minor follow up to https://github.com/canonical/charmcraft/pull/837 to take advantage of the new `namedtuple`.
=> build: use namedtuple for build plan

.github/workflows/tests.yaml, charmcraft/commands/init.py, charmcraft/templates/init-kubernetes/.gitignore.j2, charmcraft/templates/init-kubernetes/CONTRIBUTING.md.j2, charmcraft/templates/init-kubernetes/LICENSE.j2, charmcraft/templates/init-kubernetes/README.md.j2, charmcraft/templates/init-kubernetes/charmcraft.yaml.j2, charmcraft/templates/init-kubernetes/metadata.yaml.j2, charmcraft/templates/init-kubernetes/pyproject.toml.j2, charmcraft/templates/init-kubernetes/requirements.txt.j2, charmcraft/templates/init-kubernetes/src/charm.py.j2, charmcraft/templates/init-kubernetes/tests/integration/test_charm.py.j2, charmcraft/templates/init-kubernetes/tests/unit/test_charm.py.j2, charmcraft/templates/init-kubernetes/tox.ini.j2, tests/commands/test_init.py
Also fixed "simple" template (don't know why these changes didn't get into the previous PR).
=> Added a kubernetes profile to init command (CRAFT-1318).

charmcraft/reactive_plugin.py, tests/test_reactive_plugin.py
The current charm-tools version validation code is britle and may soon break as charm-tools evolves.
Fixes #864
Signed-off-by: Frode Nordahl <frode.nordahl@canonical.com>
=> reactive_plugin: Fix charm tools version validation

.github/workflows/spread.yaml
=> ci: add GHA for spread

README.md, charmcraft/commands/init.py, charmcraft/templates/init-machine/.gitignore.j2, charmcraft/templates/init-machine/CONTRIBUTING.md.j2, charmcraft/templates/init-machine/LICENSE.j2, charmcraft/templates/init-machine/README.md.j2, charmcraft/templates/init-machine/charmcraft.yaml.j2, charmcraft/templates/init-machine/metadata.yaml.j2, charmcraft/templates/init-machine/pyproject.toml.j2, charmcraft/templates/init-machine/requirements.txt.j2, charmcraft/templates/init-machine/src/charm.py.j2, charmcraft/templates/init-machine/tests/integration/test_charm.py.j2, charmcraft/templates/init-machine/tests/unit/test_charm.py.j2, charmcraft/templates/init-machine/tox.ini.j2, tests/commands/test_init.py
=> Added a machine profile to init command (CRAFT-1046).

charmcraft/reactive_plugin.py, tests/test_reactive_plugin.py
Also always log the returncode.
Fixes #804
Signed-off-by: Frode Nordahl <frode.nordahl@canonical.com>
=> reactive_plugin: Properly check returncode from charm tool

.github/workflows/spread-large.yaml, spread.yaml, tests/spread/charms/k8s-operator/task.yaml, tests/spread/charms/magma/task.yaml, tests/spread/charms/operator/task.yaml, tests/spread/charms/reactive/task.yaml
These are cronned to run on Wednesdays and Sundays at midnight.
Their only purpose is to run "pack".
=> spread: add large external charm pack tests

.github/workflows/spread.yaml, .github/workflows/tests.yaml
=> ci: move prometheus test to spread

.github/workflows/tests.yaml, requirements-jammy.txt
=> (internal) Removed macos-10.15 (deprecated) and included recent ubuntu and windows.

charmcraft/commands/store/store.py, tests/commands/test_store_api.py, tests/spread/store/resources/task.yaml
=> (charmhub) Provide a better error to the user on a login attempt when already having credentials (CRAFT-1269)

charmcraft/main.py, tests/test_main.py
=> Show (with value hidden) the auth environment variable in system details.

.editorconfig
See: https://github.com/canonical/starbase/pull/9
=> tools: editorconfig

requirements-bionic.txt, requirements-focal.txt, requirements-jammy.txt
Uses the latest source packages for python3-apt from each Ubuntu base's updates repository.
=> deps: update python-apt

charmcraft/commands/store/__init__.py, charmcraft/commands/store/client.py, charmcraft/commands/store/store.py, tests/commands/test_store_api.py, tests/commands/test_store_client.py, tests/commands/test_store_commands.py, tests/spread/store/libraries/task.yaml
If the keyring is unavailable, use a fake key.
=> charm libraries: allow anonymous fetching

requirements-dev.txt, requirements.txt, snap/hooks/configure, snap/hooks/remove, spread.yaml, tests/spread/hooks/configure/task.yaml, tests/spread/hooks/remove/task.yaml
Add snap hook to remove deprecated base images when update.
Add snap hook to remove all charmcraft base images when remove.
=> hook: clean charmcraft images when update/remove

.yamllint.yaml, .yamllintignore, pyproject.toml, setup.py, tests/commands/test_init.py, tests/test_infra.py, tools/freeze-requirements.sh, tox.ini
This adds the tox starbase config.
Note that several linters fail, so it's not appropriate to move this into CI yet.
=> tools: import tox from starbase

.github/ISSUE_TEMPLATE/bug.yaml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/task.yaml, issues.yaml
=> github: add issue templates

tests/commands/test_build.py, tests/commands/test_pack.py, tests/conftest.py, tests/test_config.py, tests/test_linters.py, tests/test_main.py, tests/test_metadata.py
Allow test cases to create multiple config yaml files.
=> tests: refactor for variable multi-file support

charmcraft/commands/init.py, charmcraft/templates/init-simple/src/charm.py.j2
=> command: add profiles descriptions and update URL

charmcraft/charm_builder.py, tests/spread/smoketests/pinned-dependencies/task.yaml, tests/test_charm_builder.py, tests/test_providers.py
Minimal fix for #1135.
A larger fix will come with 3.0.
=> builder: install pydeps and requirements simultaneously

tests/spread/store/libraries-update/task.yaml
CRAFT-1916
https://github.com/canonical/charmcraft/issues/1020
=> tests: add charm library multiple versions update test

tests/spread/store/libraries-update/task.yaml
https://github.com/canonical/charmcraft/issues/1209
=> tests: fix API json structure

charmcraft/commands/store/__init__.py, tests/commands/test_store_commands.py
=> commands(store): make create-lib work without a metadata.yaml file

charmcraft/commands/pack.py, charmcraft/package.py, tests/commands/test_pack.py, tests/test_package.py
=> pack: refactor business logic out of pack command class 

spread.yaml, tests/spread/store/resources/task.yaml
progress toward #1193 
Libraries are fixed in #1234
=> tests: fix resource spread test

requirements-dev.txt, requirements.txt, tests/spread/smoketests/parallel-build/task.yaml
Fix: https://github.com/canonical/charmcraft/issues/1138
=> tests: add parallel build test

charmcraft/commands/store/__init__.py, tests/commands/test_store_commands.py
Fix: https://github.com/canonical/charmcraft/issues/1127
=> fix(store): temporary hide package type

charmcraft/errors.py, charmcraft/extensions/__init__.py, charmcraft/extensions/_utils.py, charmcraft/extensions/extension.py, charmcraft/extensions/registry.py, charmcraft/models/charmcraft.py, tests/conftest.py, tests/extensions/test_extensions.py, tests/extensions/test_registry.py
Fix: https://github.com/canonical/charmcraft/issues/1238
=> feat(extensions): add basic support

charmcraft/commands/extensions.py, charmcraft/main.py, charmcraft/models/extension.py, completion.bash, tests/commands/test_expand_extensions.py, tests/commands/test_list_extensions.py, tests/extensions/test_extensions.py, tests/extensions/test_registry.py, tests/test_infra.py, tests/test_main.py
Add new commands expand-extensions and list-extensions
Fix: https://github.com/canonical/charmcraft/issues/1242
=> feat(extensions): add cli commands

charmcraft/application/main.py
This doesn't fix some issues that come from changes in the latest craft-application, so tests that succeeded before will likely break.
=> fix(application) use a more modern dispatcher

tests/spread/store/bundle-upload-and-release/task.yaml, tests/spread/store/charm-upload-and-release/task.yaml, tests/spread/store/libraries-update/task.yaml, tests/spread/store/libraries/task.yaml
library test failure still occurs but is fixed in #1292
=> test(spread): clean up store tests

tests/spread/charms/bundle/task.yaml, tests/spread/tools/diff_yaml.py
Use python to check yaml.
Remove charm path check that does not work.
Fixes: https://github.com/canonical/charmcraft/issues/1262
CRAFT-2052
=> fix(tests): fixes bundle spread test

tests/test_infra.py
We're using tox for black linting now.
CRAFT-2143
=> test: remove black linting from test_infra

.github/workflows/tests.yaml, snap/snapcraft.yaml
=> chore(snap): base migration from core20 to core22

charmcraft/commands/store/__init__.py, charmcraft/package.py, charmcraft/utils/package.py, setup.py, tests/commands/test_init.py, tests/commands/test_pack.py, tests/commands/test_store_commands.py, tests/test_charm_builder.py, tests/test_infra.py, tests/unit/parts/test_charm.py
Most of these changes were done by ruff's autoformatter.
=> chore(deps): update ruff and fix new linting errors

charmcraft/application/commands/__init__.py, charmcraft/application/commands/version.py, charmcraft/application/main.py, tests/commands/regression/test_help.py
includes lint fixes needed for this update
=> fix(command): backwards-compatible version command

tests/spread/store/charm-upload-and-release/task.yaml
=> tests(spread): make release test less flaky

charmcraft/utils/package.py, tests/unit/utils/test_package.py
=> fix: ignore empty requirements lines

spread.yaml, tests/spread/charms/bundle/task.yaml, tests/spread/charms/k8s-operator/task.yaml, tests/spread/charms/operator/task.yaml, tests/spread/charms/reactive/task.yaml, tests/spread/dependencies/requirements/task.yaml
This also deploys the charms/bundles for the large spread cluster
https://github.com/canonical/charmcraft/actions/runs/6695906302
=> test(spread): test-deploy charms in large spread tests

.github/workflows/tests.yaml
This is pretty much a copy-paste of the equivalent yaml from Rockcraft.
Fixes #1372
=> chore(ci): publish feature branches to edge/

.github/workflows/spread-large.yaml, README.md
=> build: rename weekly spread test

charmcraft/commands/extensions.py
This PR targets the hotfix branch to cover the legacy command.
Fixes #1411
=> fix: expand-extensions overview

requirements-dev.txt, requirements.txt, tests/unit/models/test_project.py
Requires a minor adjustment to a couple of test constants
=> build: update craft-application

tests/spread/store/charm-upload-and-release/task.yaml, tests/spread/store/resources/task.yaml
=> fix(tests): make store spread tests less flaky

charmcraft/application/commands/__init__.py, charmcraft/application/commands/store.py, charmcraft/services/store.py, charmcraft/utils/cli.py, tests/__init__.py, tests/conftest.py, tests/integration/commands/test_resource_revisions.py, tests/integration/commands/test_set_resource_architectures.py, tests/spread/store/resources/task.yaml, tests/unit/commands/test_store.py, tests/unit/services/test_store.py
Adds a command to set the architectures of an existing resource revision.
=> feat(store): set-resource-architectures command

tests/spread/smoketests/full-lifecycle/task.yaml
=> fix(spread): run tox in lifecycle spread test

charmcraft/format.py, charmcraft/jujuignore.py, tests/spread/smoketests/basic/task.yaml
See: https://github.com/canonical/charmcraft/issues/1496
Also runs an autoformat.
=> test(spread): disable almalinux tests

charmcraft/application/commands/store.py, charmcraft/metafiles/actions.py, charmcraft/utils/cli.py, pyproject.toml, tests/commands/test_store_client.py
Changes to .py are entirely done by black
=> style(autoformat): update black to 2024

.github/workflows/tests.yaml, tests/integration/commands/test_init.py
Following the GitHub runner roadmap: https://github.com/actions/runner-images/issues/9255
fixes #1508
=> ci: update macos runners

charmcraft/templates/init-kubernetes/tests/integration/test_charm.py.j2, charmcraft/templates/init-machine/tests/integration/test_charm.py.j2, charmcraft/templates/init-simple/tests/integration/test_charm.py.j2
=> fix: template integration tests

charmcraft/application/commands/__init__.py, charmcraft/application/commands/lifecycle.py
Work towards #1532
After this we still need to extend the pack command from upstream.
=> chore: replace most lifecycle commands with upstream ones

.github/workflows/spread.yaml, charmcraft/application/commands/__init__.py, charmcraft/application/commands/remote.py, charmcraft/services/__init__.py, charmcraft/services/remotebuild.py, charmcraft/utils/cli.py, tests/spread/smoketests/remote-build/task.yaml, tests/unit/models/test_project.py
This is a rebase of https://github.com/canonical/charmcraft/pull/1531 on the craft-application-on-main PR
Broken bundle build is fixed in https://github.com/canonical/charmcraft/pull/1550
CRAFT-2544
=> feat: remote build command

requirements-dev.txt, requirements-noble.txt, requirements.txt
There were several more renovate updates, this just rolls them together.
=> build(deps): update requirements

charmcraft/application/main.py, tests/unit/test_application.py
=> fix: warning deprecated prime use

.github/.jira_sync_config.yaml
- Lower case label names (root cause for everything being a marked as Bug)
- Only sync on "Triaged"
=> ci: update .jira_sync_config.yaml

charmcraft/application/commands/store.py, charmcraft/application/main.py, charmcraft/models/project.py, charmcraft/store/client.py, tests/unit/models/test_project.py, tests/unit/models/valid_charms_yaml/full-bases.yaml, tests/unit/models/valid_charms_yaml/full-platforms.yaml
=> fix: make fetch-libs + underscores work

spread.yaml, tests/spread/smoketests/basic/task.yaml
See: https://github.com/canonical/charmcraft/actions/runs/9471640681/job/26096105479?pr=1704
=> test: extend timeout for some spread tests

tests/spread/store/resources/task.yaml
upload-resource test is failing due to bug #1760.
=> tests(spread): temporarily disable failing test

charmcraft/services/provider.py, tests/unit/services/test_provider.py
=> fix(provider): forward shared cache

charmcraft/application/main.py, tests/unit/test_application.py
=> fix(app): clarify wording on 'prime' change

docs/conf.py, docs/reference/changelog.rst, docs/reference/index.rst
Fixes #1814 
Built version: https://canonical-charmcraft--1841.com.readthedocs.build/en/1841/reference/changelog/
=> docs: add and partially backfill a changelog

tests/spread/store/name-registration/task.yaml
backports fix for #1855 to 2.7
=> tests(2.7): remove bundle registration test

.github/ISSUE_TEMPLATE/bug.yaml
See: https://github.com/canonical/rockcraft/pull/684
=> ci: make charmcraft.yaml render as YAML in bug reports

setup.py
=> fix: make version work from wheel

tests/spread/store/name-registration/task.yaml
backports fix for #1855 to 3.2
=> tests(3.2): remove bundle registration test

docs/reference/changelog.rst
https://canonical-charmcraft--1902.com.readthedocs.build/en/1902/reference/changelog/#id1
=> docs(changelog): add 3.2.1

.github/workflows/spread.yaml, charmcraft/application/commands/store.py, spread.yaml, tests/spread/store/credentials/task.yaml
=> fix(store): make "whoami" work with charm-scoped credentials

charmcraft/extensions/app.py, tests/extensions/test_app.py
Now that documentation for both Rockcraft and Charmcraft is out, Django should become stable.
=> feat: make django extension stable

charmcraft/dispatch.py
=> fix(dispatch): fix the dispatch script if bins aren't kept

charmcraft/models/project.py, tests/unit/models/test_project.py
=> fix(charm-libs): better error message on bad version type

charmcraft/services/image.py
=> fix: upload all images (not just current arch) with skopeo

charmcraft/application/commands/store.py, tests/integration/commands/test_store_commands.py
=> fix(store): better error message with fetch-lib

common.mk, docs/conf.py, docs/howto/flask-async.rst, docs/howto/manage-bundles.rst, docs/howto/manage-charms.rst, docs/howto/manage-extensions.rst, docs/howto/manage-resources.rst, docs/howto/manage-revisions.rst, docs/index.rst, docs/reference/changelog.rst, docs/reference/files/actions-yaml-file.rst, docs/reference/files/bundle-yaml-file.rst, docs/reference/files/charmcraft-sample-charm.yaml, docs/reference/files/charmcraft-yaml-file.rst, docs/reuse/links.txt, docs/tutorial/flask.rst
This is a partial for #2090, containing only what is currently in rST on main. Once #2083 is merged we can do the rest.
I've also made a few tweaks to formatting related to those links
=> docs: update Juju links

common.mk
=> fix(style): ignore docs/_build

docs/reference/platforms.rst
Minor updates to the platforms reference based on [comments](https://github.com/canonical/charmcraft/pull/2080#pullrequestreview-2565319470) in #2080.
=> docs: update platforms reference

charmcraft/application/commands/test.py, docs/reference/changelog.rst
- Cherry-picks @cmatsuoka 's fix for 3.2.3
- Adds an incomplete changelog for 3.3.1
=> chore: cherry-pick fix from 3.2 and add changelog item for 3.3.1

.github/workflows/qa.yaml, .github/workflows/tests.yaml, Makefile
This is a cherry-pick of #2137 to the 3.3 hotfix branch.
=>  fix(build): fix build dependencies and CI

.github/workflows/qa.yaml, .github/workflows/tests.yaml, Makefile
This is a cherry-pick of #2137 to the 3.4 hotfix branch
=>  fix(hotfix/3.4): fix build dependencies and CI

.github/workflows/qa.yaml, .github/workflows/tests.yaml, Makefile, charmcraft/services/provider.py, tests/integration/services/test_provider.py
This is a cherry-pick of #2134 on the 3.4 branch.
Requires #2139
=> fix(hotfix/3.4): ensure /root/.cache exists

docs/howto/build-guides/pack-a-hooks-based-charm-with-charmcraft.rst, docs/howto/manage-charms.rst, docs/howto/manage-libraries.rst, docs/howto/manage-resources.rst, docs/release-notes/charmcraft-3.4.rst
Needs to be rebased to merge after https://github.com/canonical/charmcraft/pull/2151
=> chore: release 3.4.2

docs/tutorial/write-your-first-kubernetes-charm-for-a-django-app.rst
These changes emphasise the cyclical nature of the develop/pack/deploy process through headings.
=> Added some further structure to the Django tutorial

SECURITY.md
Followup to incorporate https://github.com/canonical/charmcraft/pull/2237#discussion_r2014552460.
=> docs: update charm definition in security doc

.github/workflows/schema.yaml, .github/workflows/tics.yaml, .readthedocs.yaml, Makefile, charmcraft/application/commands/lifecycle.py, charmcraft/application/commands/remote.py, charmcraft/services/remotebuild.py, common.mk, pyproject.toml, uv.lock
Not a direct merge as there is no ancestry
=> chore: bring in tics relevant changes

docs/howto/index.rst, docs/reference/commands/index.rst, docs/reference/extensions/index.rst, docs/reference/files/index.rst, docs/reference/index.rst, docs/reference/parts/index.rst, docs/reference/plugins/index.rst, docs/tutorial/index.rst
* Align main diataxis landing pages (tutorial, how-to, reference) with the standard landing page model
=> docs: align landing pages with model

MANIFEST.in, charmcraft/parts/plugins/_charm.py, charmcraft/parts/plugins/charm-constraints.txt, tests/spread/dependencies/setuptools-scm-python/charmcraft-charm.yaml, tests/spread/dependencies/setuptools-scm-python/charmcraft-poetry.yaml, tests/spread/dependencies/setuptools-scm-python/charmcraft-python.yaml, tests/spread/dependencies/setuptools-scm-python/charmcraft-uv.yaml, tests/spread/dependencies/setuptools-scm-python/constraints.txt, tests/spread/dependencies/setuptools-scm-python/pyproject.toml, tests/spread/dependencies/setuptools-scm-python/requirements.txt, tests/spread/dependencies/setuptools-scm-python/src/charm.py, tests/spread/dependencies/setuptools-scm-python/src/setuptools_scm_python.py, tests/spread/dependencies/setuptools-scm-python/task.yaml, tests/spread/dependencies/setuptools-scm-python/uv.lock, tests/unit/parts/plugins/test_charm.py
=> fix(charm): workaround to allow charmcraft-wide constraints

docs/conf.py, docs/explanation/cryptography.rst, docs/explanation/index.rst, docs/index.rst, docs/reference/plugins/poetry_plugin.rst
=> docs: add cryptographic docs

common.mk
Cherry-picks the relevant Starbase commits to update `make setup`.
=> fix: install system packages when running `make setup`

.pre-commit-config.yaml, charmcraft/application/commands/store.py, charmcraft/errors.py, charmcraft/linters.py, charmcraft/models/basic.py, charmcraft/parts/plugins/charm-constraints.txt, charmcraft/services/store.py, charmcraft/store/models.py, tests/conftest.py, tests/spread/dependencies/setuptools-scm-python/charmcraft-python.yaml, tests/spread/dependencies/setuptools-scm-python/constraints.txt, tests/spread/dependencies/setuptools-scm-python/requirements.txt, tests/spread/smoketests/full-lifecycle/task.yaml, tests/spread/smoketests/help-slug/task.yaml, tests/unit/models/test_project.py
This is a set of fixes to make for releasing 3.5.3. The actual release PR will come separately as I want to squash it :-)
=> chore: bugfixes to release 3.5.3

charmcraft/services/provider.py
=> fix: correct the permission command for craft-state
